### PR TITLE
move zexcel_s_org_rel to demos

### PR DESCRIPTION
**Pull request by larshp**
moves the structure `zexcel_s_org_rel` to demos, its only part of demos not core functionality

### CODE REVIEW

**Comment by sandraros** [comment]
LGTM

**Comment by sandraros** [comment]
@larshp I had difficulties with abapGit to pull the master because of zexcel_s_org_rel which was "simply" moved to the demos package.
Initial situation. In abapGit, I removed the repository (Advanced>Remove) to start from scratch, restarted abapGit:
image
I did Advanced>Selective Pull:
image
image
image
image

So, I deleted the program ZDEMO_EXCEL11 (which uses ZEXCEL_S_ORG_REL) and then ZEXCEL_S_ORG_REL, and did a pull. Perfectly working.

My question: is there a related issue in abapGit? (maybe [abapGit#842](https://github.com/abapGit/abapGit/issues/842)/[abapGit#2706](https://github.com/abapGit/abapGit/issues/2706))
Thanks.

**Comment by larshp** [comment]
delete `ZEXCEL_S_ORG_REL` and pull again

yea, there might be some issues moving stuff between packages and/or uninstalling

**Comment by sandraros** [comment]
@larshp Do you think it's worth adding this example to an existing abapGit issue or to add one?

**Comment by larshp** [comment]
feel free to open an issue 😄

**Comment by sandraros** [comment]
For information, issue [abapGit#4974](https://github.com/abapGit/abapGit/issues/4974) created.

**Pull request merged**
