### PR TITLE
fix read and write of the print title ranges #801

### LINKED ISSUE #801: get_print_repeat_rows/get_print_repeat_columns return initial values after reading existing Excel file
Given this [Excel file "bug_print_repeat.xlsx"](https://github.com/sapmentors/abap2xlsx/files/7191339/bug_print_repeat.xlsx) with rows and columns defined as to be repeated in each printed page (menu Page Layout > Print Titles > Rows to repeat at top = $1:$1 and Columns to repeat at left =$A:$A):
image

The following program reads the file but doesn't get the information (first popup displays "`Repeat rows: 0:0; Repeat columns: :`"), the **expected result is "`Repeat rows: 1:1; Repeat columns: A:A`"**.

For information, the two methods `get_print_repeat_rows` and `get_print_repeat_columns` work only after calling explicitly the methods `set_print_repeat_rows` and `set_print_repeat_columns` (second popup displays "`Repeat rows: 1:1; Repeat columns: A:A`").

Program to reproduce the issue:
```
REPORT.
PARAMETERS p_upfile TYPE string LOWER CASE DEFAULT 'C:\Temp\bug_print_repeat.xlsx'.
DATA gc_save_file_name TYPE string VALUE 'bug_print_repeat2.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
INITIALIZATION.
  p_path = 'C:\Temp'.
START-OF-SELECTION.
  TRY.
      DATA(reader) = NEW zcl_excel_reader_2007( ).
      DATA(excel) = reader->zif_excel_reader~load_file( p_upfile ).
      DATA(sheet) = excel->get_active_worksheet( ).
      sheet->zif_excel_sheet_printsettings~get_print_repeat_columns(
        IMPORTING
          ev_columns_from = DATA(ev_columns_from)
          ev_columns_to   = DATA(ev_columns_to) ).
      sheet->zif_excel_sheet_printsettings~get_print_repeat_rows(
        IMPORTING
          ev_rows_from = DATA(ev_rows_from)
          ev_rows_to   = DATA(ev_rows_to) ).
      MESSAGE |Repeat rows: { ev_rows_from }:{ ev_rows_to }; Repeat columns: { ev_columns_from }:{ ev_columns_to }| TYPE 'I'.
      sheet->zif_excel_sheet_printsettings~set_print_repeat_rows(
          iv_rows_from = 1
          iv_rows_to   = 1 ).
      sheet->zif_excel_sheet_printsettings~set_print_repeat_columns(
          iv_columns_from = 'A'
          iv_columns_to   = 'A' ).
      sheet->zif_excel_sheet_printsettings~get_print_repeat_columns(
        IMPORTING
          ev_columns_from = ev_columns_from
          ev_columns_to   = ev_columns_to ).
      sheet->zif_excel_sheet_printsettings~get_print_repeat_rows(
        IMPORTING
          ev_rows_from = ev_rows_from
          ev_rows_to   = ev_rows_to ).
      MESSAGE |Repeat rows: { ev_rows_from }:{ ev_rows_to }; Repeat columns: { ev_columns_from }:{ ev_columns_to }| TYPE 'I'.
      lcl_output=>output( excel ).
    CATCH cx_root INTO DATA(lx_root).
      MESSAGE lx_root TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
```

### PR DESCRIPTION
**Pull request by bigld**
closes #801

Print Titles are (now) stored as 1 dimensional ranges like $A:$F which was not recognised by the regex
To not break any existing coding the 1 dimensional read must be activated via parameter

### CODE REVIEW

**Review by sandraros — CHANGES_REQUESTED** [review]
There are many changed lines, most of them seem to be only due to pretty printer. Is it possible to split the changes into 2 PRs? A first one with minimal code to just fix #801 and another one with the pretty printer? Thanks for your help 👍
I also see that I can't add a commit to automatically merge the latest commits. As Lars said, could you authorize us by setting "[allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), it's usually enabled by default". 👍

**Comment by bigld** [comment]
I'll split them up!
The PR comes from an organisation - I thinks that's the reason for the missing auth?!?

**Comment by sandraros** [comment]
In the link, they are talking about "user-owned forks", no mention about organizations. I could just find this github "issue" about [allowing edits for maintainers in organization repositories](https://github.com/isaacs/github/issues/1681) saying "it will not work unless the maintainer is explicitly added as a contributor to the source repository", which doesn't make a lot of sense to me...

**Review by sandraros — CHANGES_REQUESTED** [review]
Thanks for the "Undo PPs" on class `zcl_excel_common`. I "added" the "Undo PP 7" for the class `zcl_excel_reader_2007`, but I could do it only in my own [branch](https://github.com/sandraros/abap2xlsx/tree/issue_801). Could you check and add the changes to your own branch so that I can merge (my tests were okay). Thanks 👍 And we'll integrate the Pretty Print PR afterwards.

**Comment by bigld** [comment]
sorry didn't see this file...

**Review by sandraros — CHANGES_REQUESTED** [review]
I don't know what happened, few recent commits are gone (new methods `load_style_font`, `load_worksheet_ignored_errors`, etc.) Could you check? Thanks 👍

**Review by sandraros — CHANGES_REQUESTED** [review]
There's still some old code in `load_style_fonts` of `zcl_excel_reader_2007`. You may use DIFF in ZABAPGIT or in github to make sure you don't change other code. After that, I think we're good.

**Comment by sandraros** [comment]
As I said in my previous comment, I propose that you do the changes in `zcl_excel_reader_2007` shown in this [diff](https://github.com/sandraros/abap2xlsx801/commit/14c2f54ff07fbc65fd130670fdeee208ca9bccfa). Thank you!

**Pull request closed without merging**
