### PR TITLE
change REFRESH to CLEAR

### PR DESCRIPTION
**Pull request by larshp**
and remve REFRESH if the variable is always empty

### CODE REVIEW

**Review by sandraros — CHANGES_REQUESTED** [review]
Don't you want to replace REFRESH from everywhere? It's still present in classes ZCL_EXCEL_CONVERTER*.

**Review by sandraros — APPROVED** [review]
LGTM 👍
EDIT: I was too fast, sorry, I let you finish ;-)

**Comment by larshp** [comment]
REFRESH rule in https://rules.abaplint.org/obsolete_statement/ enabled

I was focusing on Steampunk, so the first batch was partial 🥤

**Comment by larshp** [comment]
finished 🏁

**Pull request merged**
