### PR TITLE
Add a new column width calculation

### PR DESCRIPTION
**Pull request by guillaumegarcia13**
Change of formula for cell width

### CODE REVIEW

**Comment by gregorwolf** [comment]
Please update your SAPlink version to the latest available from the build directory. It will export the Slinkee with less meta data and that will cause not so many changes. So we can see much more easily in the diff which real changes you did. Please then re-submit your merge request.

**Comment by guillaumegarcia13** [comment]
Hi,
I use SAPlink 0.1.5 alpha 2. Is there a newer one?
I checked https://www.assembla.com/code/saplink/subversion/nodes/387/trunk/build/SAPlink_Daily.nugg but it also refer to SAPlink 0.1.5 alpha 2

Thx.

**Comment by gregorwolf** [comment]
The Daily build is the right one. Unfortunately the version counter is still set manually. If you like you can improve ZAKE to support replacing the Version with the revision ID. :-)

**Comment by guillaumegarcia13** [comment]
One thing at a time...  :)
Such a pity SAPLink is not hosted on GitHub  ;-(

**Comment by ivanfemia** [comment]
Thanks Gregor for the advice...
I will wait for the update of the pull request...

Thanks 
Ivan

**Comment by ivanfemia** [comment]
I really like this feature. 
Are you planning to resubmit a new pull request using the latest SAPlink version?

**Comment by chrassig** [comment]
Hi Guillaume,

we were working on an improved version of the calculation of column widths in the previous days. We only saw your suggestion today.

Ivan accepted our logic into the ABAP2XLSX repository today.
https://github.com/ivanfemia/abap2xlsx/pull/310

If you have any suggestions to improve the new logic, please feel free to contribute. I guess all of us would like a version that includes the benefits from your version and from our version.

Best regards,
Christian

**Comment by guillaumegarcia13** [comment]
Hi,
Sorry for the delay, been busy lately.
@chrassig: your solution seems to be way better than the little addition I made, I think we can close this pull request.

Best regards,
Guillaume

**Comment by ivanfemia** [comment]
Guillaume.
Thank you for your support and help, really appreciated!

**Pull request closed without merging**
