### PR TITLE
Header/footer image and table on Excel 2007 write has invalid relationships

### PR DESCRIPTION
**Pull request by darnoc312**
solving #1113

### CODE REVIEW

**Comment by gregorwolf** [comment]
@darnoc312 Is there a sample where this improvement can be checked?

**Comment by darnoc312** [comment]
Hello,

please try the following version of ZTEST_EXCEL_IMAGE_HEADER.
The 'Hello world' of the second sheet is now part of a table.
The occurence of a table and header/footer in one sheet causes the problem.
The program only works after the patch is done.

```abap
REPORT ztest_excel_image_header.

DATA: lo_excel     TYPE REF TO zcl_excel,
      lo_worksheet TYPE REF TO zcl_excel_worksheet,
      lo_drawing   TYPE REF TO zcl_excel_drawing,
      ls_key       TYPE wwwdatatab,
      ls_header    TYPE zexcel_s_worksheet_head_foot,
      ls_footer    TYPE zexcel_s_worksheet_head_foot,
      lv_content   TYPE xstring.


DATA: ls_io TYPE skwf_io.

CONSTANTS: gc_save_file_name TYPE string VALUE 'Image_Header_Footer.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.

  " Creates active sheet
  CREATE OBJECT lo_excel.

**********************************************************************
*** Header Center
  " create global drawing, set position and media from web repository
  lo_drawing = lo_excel->add_new_drawing( ip_type = zcl_excel_drawing=>type_image_header_footer ).

  ls_key-relid = 'MI'.
  ls_key-objid = 'SAPLOGO.GIF'.
  lo_drawing->set_media_www( ip_key = ls_key
                            ip_width = 166
                            ip_height = 75 ).
**********************************************************************
  ls_header-center_image = lo_drawing.


**********************************************************************
*** Header Left
  " create global drawing, set position and media from web repository
  lo_drawing = lo_excel->add_new_drawing( ip_type = zcl_excel_drawing=>type_image_header_footer ).

  ls_key-relid = 'MI'.
  ls_key-objid = 'SAPLOGO.GIF'.
  lo_drawing->set_media_www( ip_key = ls_key
                             ip_width = 166
                             ip_height = 75 ).


  ls_header-left_image = ls_footer-left_image = lo_drawing.
  ls_header-left_value = 'Hallo'.
* Makes the "Hallo" in the print preview more visible behind the SAP logo
* ls_header-left_font-name = 'Tahoma'.
* ls_header-left_font-size = 30.
* ls_header-left_font-bold = 'X'.
  lo_worksheet = lo_excel->get_active_worksheet( ).

  lo_worksheet->sheet_setup->set_header_footer( ip_odd_header = ls_header
                                                ip_odd_footer = ls_footer ).

**********************************************************************
*** Normal Image
  " create global drawing, set position and media from web repository
  lo_drawing = lo_excel->add_new_drawing( ).
  lo_drawing->set_position( ip_from_row = 3
                            ip_from_col = 'B' ).

  ls_key-relid = 'MI'.
  ls_key-objid = 'SAPLOGO.GIF'.
  lo_drawing->set_media_www( ip_key = ls_key
                             ip_width = 166
                             ip_height = 75 ).

  " assign drawing to the worksheet
  lo_worksheet->add_drawing( lo_drawing ).

**********************************************************************
**********************************************************************
* New sheet
  lo_worksheet = lo_excel->add_new_worksheet( 'Sheet2' ).

*  " Add some content otherwise the error "nothing to be printed" is shown
*  lo_worksheet->set_cell( ip_column = 'B' ip_row = 3 ip_value = 'Hello world' ).

* Begin of the table for demonstration
  DATA: BEGIN OF ls_demo,
          text TYPE string,
        END OF ls_demo,
        ls_settings TYPE zexcel_s_table_settings,
        lt_demo     LIKE TABLE OF ls_demo.

  CLEAR ls_settings.
  ls_settings-top_left_row = 3.
  ls_settings-top_left_column = 'B'.

  ls_demo-text = 'Hello world'.
  APPEND ls_demo TO lt_demo.
  lo_worksheet->bind_table( EXPORTING
                              ip_table          = lt_demo
                              is_table_settings = ls_settings ).
* End of the table

**********************************************************************
*** Header Left
  " create global drawing, set position and media from web repository
  lo_drawing = lo_excel->add_new_drawing( ip_type = zcl_excel_drawing=>type_image_header_footer ).

  ls_key-relid = 'MI'.
  ls_key-objid = 'SAPLOGO.GIF'.
  lo_drawing->set_media_www( ip_key = ls_key
                             ip_width = 166
                             ip_height = 75 ).


  CLEAR ls_header.
  ls_header-left_image = ls_footer-left_image = lo_drawing.

  lo_worksheet->sheet_setup->set_header_footer( ip_odd_header = ls_header ).


*** Create output
  lcl_output=>output( lo_excel ).
```

**Comment by gregorwolf** [comment]
Do the samples that can be found in the [demos](https://github.com/search?q=repo%3Aabap2xlsx%2Fdemos%20set_header_footer&type=code) repository cover your improvement?

**Comment by darnoc312** [comment]
The program ZTEST_EXCEL_IMAGE_HEADER is a part of the demos repository (the last one in the list).
But i need a program with a table and header/footer in one sheet.
Therefore the 'Hello world' of the second sheet becomes now part of a very small table.
That is the minimum change to the original program to demonstrate the problem.

**Review by sandraros — APPROVED** [review]

**Pull request merged**
