### PR TITLE
remove DTEL INTTYPE

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**

### CODE REVIEW

**Comment by AndreaBorgia-Abo** [comment]
@sandraros what is your opinion on this? See also [my comment](https://github.com/abap2xlsx/abap2xlsx/issues/692#issuecomment-981794156) in #692

**Comment by sandraros** [comment]
LGTM for ZCL_EXCEL_CONVERTER. Will you add ZEXCEL_S_CONVERTER_FCAT too in this PR? Will you "un-draft" this PR?

**Review by AndreaBorgia-Abo — COMMENTED** [review]
changes are as expected

**Comment by AndreaBorgia-Abo** [comment]
Done.

When I'll grow up, I'll find out why abapGit is pestering me about /.abapgit.xml and /.apack-manifest.xml :/

**Review by sandraros — APPROVED** [review]
LGTM 👍

**Pull request merged**
