### PR TITLE
Fix diff due to abapGit changes

### PR DESCRIPTION
**Pull request by sandraros**

### CODE REVIEW

**Comment by AndreaBorgia-Abo** [comment]
Anything in particular to watch out for?

**Comment by sandraros** [comment]
When I pulled abap2xlsx, abapGit (latest version) has reported Diff for these 5 objects. Could you check that it's the same for you?

**Comment by AndreaBorgia-Abo** [comment]
I have not seen anything wrong, should I try with an empty container?
Of course, in that case, after new PR on the demos repo.

**Comment by sandraros** [comment]
I'm not sure. I need to check again since all demo programs are moved to the repository abap2xlsx/demos.

**Comment by sandraros** [comment]
No more issue. Abandoning this pull request.

**Pull request closed without merging**
