### PR TITLE
Update of DEMO31 as advised in #558

### PR DESCRIPTION
**Pull request by AlexandreHT**
Set_auto_size needs lo_worksheet->calculate_column_widths( ) to work

### CODE REVIEW

**Review by AndreaBorgia-Abo — APPROVED** [review]
Cool! I ran into #646 a while ago and this looks like a compact solution, thanks.
Tested with LibreOffice, by the way.

**Comment by dbausch85** [comment]
I think ZCL_EXCEL_WRITER_2007->CREATE_XL_SHEET (Row 461) is wrong. 

`IF NOT lo_column_iterator IS BOUND`

should be changed to:

`IF lo_column_iterator IS BOUND`

Same game for ZCL_EXCEL_WRITER_HUGE_FILE (Row 306).

**Comment by AndreaBorgia-Abo** [comment]
@dbausch85 how is it related to this PR?

**Comment by AlexandreHT** [comment]
@dbausch85 I don't see how your comment is related to this PR, I just changed ```zdemo_excel31``` to make it work.

**Review by gregorwolf — APPROVED** [review]

**Comment by gregorwolf** [comment]
Thank you @AlexandreHT for the contribuiton

**Pull request merged**
