### PR TITLE
Issue #783 - Conditional Formatting

### PR DESCRIPTION
**Pull request by hardyp**
This adds code to handle conditional formatting whereby the format of a cell depends on the text string at the start of the cell value.

All I did was add code, but the comparison is showing loads of totally unrelated changes in methods I did not touch. I only changed the CREATE_XL_SHEET method. What's going on?

### CODE REVIEW

**Comment by larshp** [comment]
see https://github.com/sapmentors/abap2xlsx/issues/780

**Comment by AndreaBorgia-Abo** [comment]
As already noted above, pretty print settings are one possible culprit. The other notable offender is using SE80 and friends instead of Eclipse. Learnt that the hard way :(

**Comment by AndreaBorgia-Abo** [comment]
@hardyp #781 was merged and resulted in some conflicts, sorry for the inconvenience.
Once those are fixed, going forward we should have less trouble with formatting than what you encountered.

**Comment by hardyp** [comment]
I have no idea what I have to do here. Presumably the conflicts were all because of the "pretty printer" indenting some lines and changing the case of some words and of course Git sees this as a difference because it is just comparing the text. Anyway the desired end result is just some added lines ... how do I proceed?

**Comment by AndreaBorgia-Abo** [comment]
So, the first thing in general would be to create the PR from a feature branch on your fork, not from the master. This way, you're able to run "git fetch upstream" and "git merge upstream/master" when you want to update your fork and, crucially, the feature branch would be kept safe from other influences. You could also have more than one outstanding PR on your repo, this way.

Once you have done that, your changes in a feature branch should produce a much smaller set of differences.
In your case, only the block between lines 4837 and 4868.

While we're at it, comments like line 4835 and line 4870 ( #782 ) are not needed, much like the contrary: with git, we're able to find out who wrote what and when without the legacy comments traditionally used in SAP landscapes. The following explanation block (4837-4843), on the other hand, is very much appreciated.

**Review by AndreaBorgia-Abo — CHANGES_REQUESTED** [review]
So, the first thing in general would be to create the PR from a feature branch on your fork, not from the master. This way, you're able to run "git fetch upstream" and "git merge upstream/master" when you want to update your fork and, crucially, the feature branch would be kept safe from other influences. You could also have more than one outstanding PR on your repo, this way.

Once you have done that, your changes in a feature branch should produce a much smaller set of differences.
In your case, only the block between lines 4837 and 4868.

While we're at it, comments like line 4835 and line 4870 ( #782 ) are not needed, much like the contrary: with git, we're able to find out who wrote what and when (with "git blame") without the legacy comments traditionally used in SAP landscapes. The following explanation block (4837-4843), on the other hand, is very much appreciated.

Bonus points if the additional functionality can already be tested with one of the supplied demos, possibly with a minor modification.

**Comment by hardyp** [comment]
I have no idea what I am doing, so I am going to install the latest version of the project on my development system - make the change again in my fork - and this time stop myself from doing the "pretty print".
I quite agree with not having comments with issue numbers - I always delete such comments from my real system. I was just following what seemed to have gone before.

**Pull request closed without merging**
