### PR TITLE
Performance Update (new writer)

### PR DESCRIPTION
**Pull request by mvcube**
Hi Ivan,

these are my first steps into GITHub land. I've just downloaded a single nugget from the SAP system with all components, updated or not. I've no idea how to split that nugget into a sequence of .slink files to match the repository structure.

Marcus

P.S.: I made some mistakes during my first branch creation. This one should be better.

### CODE REVIEW

**Comment by ivanfemia** [comment]
Hi Markus could you please list the objects that you changed so I can check these.

Thank you.
Ivan

In order to create a pull request you can fork the project and export from your abap system just the files that you changed for your improvement/enhancement/bugfix.
In this way, when you'll request the pull request just the edited files will be included in the request.

Ivan

**Comment by ivanfemia** [comment]
Hi Marcus,

thank for your pull request, could you please commit just the slenkee files (.slnk) that you have modified in your enhancement.
It makes us easier to include it in the main stream...

Thank you
Ivan

**Comment by mvcube** [comment]
I don't have any slenkees yet. It will take some time to identify all the relevant changes on the SAP system and export the stuff. The reason is that I haven't just updated a few objects but I did many updates in response to code inspector complaints. I'll try to isolate the most relevant ones and report back here. Stay tuned!

**Comment by gregorwolf** [comment]
Dear Markus,
perhaps you use the Report ZAKE_SVN_A2X to export all the Slinkees into the repository you've cloned from git and use diff to identify the changes. If they don't break anything, this improvements would also be welcome.
Best regards
Gregor

**Comment by mvcube** [comment]
Gregor, any hints where I can find ZAKE_SVN_A2X and what it does? is it part of ABAP2XLSX as the name suggests? I've no access to the SAP system until January so you'll need to be patient anyway.

Marcus

**Comment by gregorwolf** [comment]
Your find find the Slinkee of ZAKE_SVN_A2X  in the /ZA2X/PROG folder of the repository. To use it you have to install in addition to SAPlink ZAKE from http://zake.saplink.org

**Comment by ivanfemia** [comment]
Marcus, 

no problem, I appreciate your collaboration.
Please ask if you need any info or tips.

Ivan

**Pull request closed without merging**
