### PR TITLE
Fix CSV Export with date and time in excel format

### PR DESCRIPTION
**Pull request by oberhm**
fixes the issue #1134
If the csv exporter is used, the date and time fields get converted to the excel format.
This leads to problem when opening the csv file not in excel

### CODE REVIEW

**Comment by sandraros** [comment]
Thank you for volunteering in abap2xlsx. I don't have time to look at it before middle of next week, but I feel that it's a little bit dangerous to change in the method `set_cell` of `zcl_excel_worksheet` while the issue is in `zcl_excel_writer_csv`, as it may impact all other classes and client programs. The format must internally remain like `45155` instead of `17.08.2023` (to reuse your example). I'm not sure there is a bug, let me ask you a question in the original issue (#1134).

**Comment by oberhm** [comment]
Hi.
I agree with you, that these change is very dangerous.

But the variable lv_data_type is set two times in the coding before:
- if ip_data_type is supplied
- if the lv_value_type is a kind of stringlike

The lv_data_type is transferred to the sheet content field data_type

I could not see any big problem, if the field data_type is set correctly every time.
Actually the field data_type is empty in case of all data types except type stringlike.

I will response in the issue with an example.

**Comment by oberhm** [comment]
This request is obsolet. see comments in #1134

**Review by sandraros — APPROVED** [review]
LGTM Thank you! 👍

**Pull request merged**
