### PR TITLE
Header Footer Image

### PR DESCRIPTION
**Pull request by mfallen**
including a test program

### CODE REVIEW

**Comment by mfallen** [comment]
Hopefully now fine, seems I have not the actual version in my system, sorry!

**Comment by gregorwolf** [comment]
Hi @mfallen,
I've imported your branch into my system but there is an issue that the Class zcl_abap_bitmap isn't found. Please add that to the pull request.
CU
Gregor

**Comment by mfallen** [comment]
HI @gregorwolf, Damn, this is Something very old in my system. Will Update tomorrow without this class (Not needed)

**Comment by mfallen** [comment]
@gregorwolf  - program is updated, missed to delete the class!

**Comment by gregorwolf** [comment]
Hope we get closer. Get this error now:

Program ZTEST_EXCEL_IMAGE_HEADER
Field "TYPE_IMAGE_HEADER_FOOTER" is unknown.

Seems you have to add your changes to zcl_excel_drawing=>type_image_header_footer.

**Comment by mfallen** [comment]
Next check ;-)

**Comment by gregorwolf** [comment]
It dumps now in ZCL_EXCEL_WRITER_2007->CREATE_XL_DRAWINGS_VML as you use CRM_IC_XML_STRING2XSTRING. Please replace it with SCMS_STRING_TO_XSTRING.

**Comment by gregorwolf** [comment]
And maybe you get also a NetWeaver ABAP Developer Edition someday :-).

**Comment by mfallen** [comment]
As well corrected, that part of coding I re-used from Marios Toumanis...arrgh

**Comment by mfallen** [comment]
Danke @gregorwolf  Gregor! War zwar eine schwere Geburt, aber jeder fängt mal klein an ;-)

Grüße
Michael

**Comment by gregorwolf** [comment]
Ich danke Dir recht herzlich.

**Pull request merged**
