### PR TITLE
add cloning \w method for cloning sheets

### PR DESCRIPTION
**Pull request by sz3lbi**
Issue: https://github.com/abap2xlsx/abap2xlsx/issues/1004

Added the `zcl_excel_base` prototype class, implemented deep cloning in Excel components, added the `clone_worksheet` method in the main Excel class.

### CODE REVIEW

**Comment by larshp** [comment]
note that abap2xlsx aims for 702 compatibility, so inline declarations are not possible

**Comment by sz3lbi** [comment]
> note that abap2xlsx aims for 702 compatibility, so inline declarations are not possible

Working on it.

**Comment by sz3lbi** [comment]
Please review.

**Comment by sandraros** [comment]
I created the below program to test your PR and it produced the error `15_08_RangeFromReader.xlsx Failed to match the regular expression.` To reproduce, you must run `ZDEMO_EXCEL` before running the demo program. It happens in the method `GET_SHEET_TITLE` of `ZCL_EXCEL_RANGE`, which is called by `SET_TITLE` of `ZCL_EXCEL_WORKSHEET`.

I'm not sure why it's needed to change the logic, can't we keep the same as before?

NB: I also just added a commit to your branch to cancel very minor changes which are not related to cloning a sheet, it shouldn't produce any side-effect.
```abap
  TRY.
      DATA(file_names) = VALUE string_table(
      ( |15_31_AutosizeWithDifferentFontSizesFromReader.xlsx            | )
      ( |15_24_Sheets_with_different_default_date_formatsFromReader.xlsx| )
      ( |15_13_MergedCellsFromReader.xlsx                               | )
      ( |15_08_RangeFromReader.xlsx                                     | )
      ( |15_07_ConditionalAllFromReader.xlsx                            | )
      ( |15_05_ConditionalFromReader.xlsx                               | )
      ( |15_04_SheetsFromReader.xlsx                                    | )
      ( |15_03_iTabFromReader.xlsx                                      | )
      ( |15_02_StylesFromReader.xlsx                                    | )
      ( |15_01_HelloWorldFromReader.xlsx                                | )
      ( |Image_Header_Footer.xlsx                                       | )
      ( |Comments.xlsx                                                  | )
      ( |49_Bind_Table_Conversion_Exit.xlsx                             | )
      ( |ABAP2XLSX Inheritance.xlsx                                     | )
      ( |40_Printsettings.xlsx                                          | )
      ( |39_Charts.xlsx                                                 | )
      ( |38_SAP-Icons.xlsx                                              | )
      ( |37- Read template and output.xlsx                              | )
      ( |36_DefaultStyles.xlsx                                          | )
      ( |35_Static_Styles.xlsx                                          | )
      ( |34_Static Styles_Chess.xlsx                                    | )
      ( |33_autofilter.xlsx                                             | )
      ( |31_AutosizeWithDifferentFontSizes.xlsx                         | )
      ( |30_CellDataTypes.xlsx                                          | )
      ( |27_ConditionalFormatting.xlsx                                  | )
      ( |24_Sheets_with_different_default_date_formats.xlsx             | )
      ( |23_Sheets_with_and_without_grid_lines.xlsx                     | )
      ( |22_itab_fieldcatalog.xlsx                                      | )
      ( |21_BackgroundColorPicker.xlsx                                  | )
      ( |19_SetActiveSheet.xlsx                                         | )
      ( |18_BookProtection.xlsx                                         | )
      ( |17_SheetProtection.xlsx                                        | )
      ( |16_Drawings.xlsx                                               | )
      ( |14_Alignment.xlsx                                              | )
      ( |13_MergedCells.xlsx                                            | )
      ( |12_HideSizeOutlineRowsAndColumns.xlsx                          | )
      ( |10_iTabFieldCatalog.xlsx                                       | )
      ( |09_DataValidation.xlsx                                         | )
      ( |08_Range.xlsx                                                  | )
      ( |07_ConditionalAll.xlsx                                         | )
      ( |06_Formulas.xlsx                                               | )
      ( |05_Conditional.xlsx                                            | )
      ( |04_Sheets.xlsx                                                 | )
      ( |03_iTab.xlsx                                                   | )
      ( |02_Styles.xlsx                                                 | )
      ( |01_HelloWorld.xlsx                                             | ) ).
      DATA(lv_workdir) = ``.
      cl_gui_frontend_services=>get_sapgui_workdir( CHANGING sapworkdir = lv_workdir ).
      cl_gui_cfw=>flush( ).

      LOOP AT file_names INTO DATA(file_name).
        file_name = replace( val = file_name regex = ' +$' with = '' ).
        DATA(file_path) = lv_workdir && '\' && file_name.
        DATA(reader) = NEW zcl_excel_reader_2007( ).
        DATA(workbook) = reader->zif_excel_reader~load_file( file_path ).

        DATA(iterator) = workbook->get_worksheets_iterator( ).
        TYPES ty_sheets TYPE STANDARD TABLE OF REF TO zcl_excel_worksheet WITH EMPTY KEY.
        DATA(sheets) = VALUE ty_sheets( ).
        WHILE iterator->has_next( ).
          DATA(sheet) = CAST zcl_excel_worksheet( iterator->get_next( ) ).
          APPEND sheet TO sheets.
        ENDWHILE.

        LOOP AT sheets INTO sheet.
          DATA(new_sheet) = workbook->clone_worksheet( sheet ).
          new_sheet->set_title( sheet->get_title( ) && '2' ).
        ENDLOOP.

        DATA(writer) = NEW zcl_excel_writer_2007( ).
        DATA(xlsx_content) = writer->zif_excel_writer~write_file( workbook ).
        file_path = lv_workdir && '\1015_' && file_name.
        PERFORM write_bin_file USING file_path xlsx_content.
      ENDLOOP.
    CATCH zcx_excel INTO DATA(error).
      MESSAGE |{ file_name } { error->get_text( ) }| TYPE 'I' DISPLAY LIKE 'E'.
  ENDTRY.
FORM write_bin_file
      USING
        i_filename      TYPE csequence
        i_file_xstring  TYPE xstring.
  DATA lt_xstring TYPE TABLE OF x255.
  DATA l_length TYPE i.
  DATA l_filename TYPE string.
  l_filename = i_filename.
  CALL METHOD cl_swf_utl_convert_xstring=>xstring_to_table
    EXPORTING
      i_stream = i_file_xstring
    IMPORTING
      e_table  = lt_xstring.
  l_length = xstrlen( i_file_xstring ).
  CALL METHOD cl_gui_frontend_services=>gui_download
    EXPORTING
      bin_filesize = l_length
      filename     = l_filename
      filetype     = 'BIN'
    CHANGING
      data_tab     = lt_xstring.
ENDFORM.
```

**Comment by sz3lbi** [comment]
I've reproduced the error you described and it turned out that my regex was not written correctly and that was a reason of an exception.  
Additionally, I discovered another problem which has been fixed as well.

I was not able to test the following files and they were not available in the Web Repository. I commented them out, so you can test them youself to be sure.
- `44_iTabNotEmpty.csv`
- `44_iTabEmpty.csv`
- `ABAP2XLSX Inheritance.xlsx`
- `40_Printsettings.xlsx`
- `37- Read template and output.xlsx`
- `28_HelloWorld_Sheet1.csv`
- `28_HelloWorld_Sheet2.csv`

> I'm not sure why it's needed to change the logic, can't we keep the same as before?

As far as I remember, when you read ranges from an `xlsx` file, they are provided to in the form of strings.
When the worksheet is cloned, and its ranges at the same time, the worksheet title in all of those ranges has to be changed. Without the regex-logic I was not able to read only the worksheet title from them to replace it easily. I would have to replace the whole range value.
As I already created those methods for cloning, I replaced the logic in the `set_title` method as well. It is a bit shorter, but you can restore the old logic if you prefer it.

**Comment by sz3lbi** [comment]
> Without the regex-logic I was not able to read only the worksheet title from them to replace it easily.

As the `clone` method is public, ranges can be cloned separately from worksheets - in those cases the regex logic is necessary.  
That's what I meant.

**Comment by sz3lbi** [comment]
Anything in this topic?

**Comment by sandraros** [comment]
That fixed the issue. I compared the sheets manually, and saw these differences:

- `1015_04_Sheets.xlsx`: the worksheet cloned from the hidden `Sheet3` is made visible
- The Excel feature "Data Validation" has been broken, but it happens just by running the demo programs (just run `ZDEMO_EXCEL` to generate all the files), not even cloning. When opening any of the 2 files below, this pops up (it doesn't happen with the current `main` branch):
  image
  - `03_iTab.xlsx`: in cell 'Internal table'!C4, the list of possible values doesn't show up
  - `09_DataValidations.xlsx`: in cell 'Table with Data Validation'!A12, the list of possible values doesn't show up
  - `27_ConditionalFormatting.xlsx`: in cell 'Conditional formatting'!C2, the list of possible values doesn't show up
- `1015_12_HideSizeOutlineRowsAndColumns.xlsx`: the cloned worksheet makes all columns visible (`zdemo_excel12`: possibly `lo_worksheet->zif_excel_sheet_properties~hide_columns_from = 'M'.`?)
- `1015_22_itab_fieldcatalog.xlsx`: the cloned worksheet loses the "white background" (`zdemo_excel22`: possibly `lo_worksheet->zif_excel_sheet_properties~set_style( lv_style_guid ).`?)
- `1015_33_autofilter.xlsx`: the cloned worksheet loses the filters
- `1015_39_Charts.xlsx`: there's an Excel error when opening the workbook
- `1015_40_PrintSettings.xlsx`: the print settings "do not repeat" are not cloned

Fixing all these differences may take a while, maybe we can simply say that the worksheet cloning doesn't support those features.

Note that few differences are not due to cloning but to features working in the writer but not in the reader (it can be seen also by running `zdemo_excel37`), so cloning can't work on these features (as expected):
- Tables (colors, column formulas)
  - `1015_10_iTabFieldCatalog.xlsx`
  - etc.

**Comment by sandraros** [comment]
@AndreaBorgia-Abo If you have some time, could you give your opinion about the code concerning the creation of the super class `zcl_excel_base`, many classes will inherit from it. I think it's something smart for limiting the number of modifications but not so good from design perspective. I don't know if this can be problematic (whatever it's for existing installations, for maintenance...)

**Comment by AndreaBorgia-Abo** [comment]
@sandraros maybe we could discuss it during the [Community Call](https://github.com/abap2xlsx/abap2xlsx/issues/749), otherwise I'm very short on time right now and, more to the point, I'm not sure I can provide reasonable feedback on OO design issues in a reasonable timeframe.

**Pull request closed without merging**
