### PR TITLE
remove remaining usage of XFELD

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**
followup #714
WIP #692

### CODE REVIEW

**Comment by larshp** [comment]
XFELD is replaced with CHAR1, which I guess looses the information that its a field intended to have "X" or " " ?

perhaps we should add a ZEXCEL_FLAG/ZEXCEL_BOOLEAN instead?

**Comment by AndreaBorgia-Abo** [comment]
> XFELD is replaced with CHAR1, which I guess looses the information that its a field intended to have "X" or " " ?
> perhaps we should add a ZEXCEL_FLAG/ZEXCEL_BOOLEAN instead?

I'm not sure it's worth it: a local variable with a single IF was affected and rewriting was trivial.
Going forward, we should probably stick to abap_true and abap_false.

EDIT: my apologies, I mixed up two different changes when replying here! The "boolean" is dealt with in #774 
I have to recheck how ZEXCEL_S_STYLE_PROTECTION and ZEXCEL_SHEET_SHOWZEROS are used before merging.

**Comment by AndreaBorgia-Abo** [comment]
After reviewing #714 and #721 (also related to XFELD), here is a re-check of this PR:

* zexcel_s_style_protection
    locked: set to c_protection_locked (1) in ZCL_EXCEL_READER_2007, method LOAD_STYLES (safer now),
        set to c_protection_locked (1) in class ZCL_EXCEL_STYLE_PROTECTION, method constructor (again, safer)
    hidden: 
        multiple uses in class ZCL_EXCEL_WRITER_2007, method CREATE_XL_STYLES but they all look in line with the values

* zexcel_sheet_showzeros:
    in class ZCL_EXCEL_WRITER_2007, method CREATE_XL_SHEET it is checked against abap_false (a blank space),
    but initialized to c_hidezero in ZDEMO_EXCEL4, unsurprisingly this did not work even before this PR
    (Sheet4, B3 = 0 but still visible; tested with Libreoffice under Linux... will have to retest with Excel proper)
    
@larshp I'll have another look at this demo in a few days but I suppose I could roll a fix together with this PR, what do you say?
Together with the fixes mentioned in #721, of course.

**Comment by AndreaBorgia-Abo** [comment]
Fixed the previous comment (wrong method), tested both master branch and PR branch with ZDEMO_EXCEL4, as-is and forcing zif_excel_sheet_properties~show_zeros to X. In both cases, using Excel on Windows instead of Libreoffice on Linux, the zero value B3 cell is consistently hidden (demo as-is) or shown (forced to X).
So, the PR is good as it stands now: nothing to fix here other than perhaps the [second use of protected](https://github.com/sapmentors/abap2xlsx/pull/721#issuecomment-878601308) in #721 and maybe change C_HIDEZERO from empty string to single blankspace to be consistent with the check in CREATE_XL_SHEET.... but these might as well happen at another moment.

**Comment by sandraros** [comment]
What about merging these changes now?

**Comment by AndreaBorgia-Abo** [comment]
After @larshp [comment](https://github.com/sapmentors/abap2xlsx/pull/775#issuecomment-877660342) I was kind of waiting for feedback related to the following checks. No other pending work on my side.

**Comment by AndreaBorgia-Abo** [comment]
Thanks :)

**Pull request merged**
