### PR TITLE
remove "BOOLEAN" domain

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**
this should take care of the remaining uses of the BOOLEAN domain,
as verified with Eclipse, standard SE11, and also grep.

WIP #692

### CODE REVIEW

**Review by AndreaBorgia-Abo — COMMENTED** [review]
change is as expected

**Comment by AndreaBorgia-Abo** [comment]
@larshp could you please merge this?

**Comment by AndreaBorgia-Abo** [comment]
thanks.

**Comment by larshp** [comment]
I dont really have much time to spend on this project 😞 ...

**Pull request merged**
