### PR TITLE
Copy Comments from Excel Template + BugFix Autofil

### PR DESCRIPTION
**Pull request by rotda**
[FEATURE] Added Functions which are copy the comments + vmldrawings from the excel template to target
[BUGFIX] Autofilter are not on the correct row if you have an header line

You can test it with Report ZDEMO_EXCEL29 and a xlsm Workbook with Comments 

Please Review 

Cheers
Daniel

### CODE REVIEW

**Comment by larshp** [comment]
#547 ?

**Comment by rotda** [comment]
yes #547 ( zcl_excel_reader_2007.clas.abap row 1982) and #546 
plus the functions that the comments will be copied from the source excel

**Comment by ivanfemia** [comment]
rotda 
can you provide a demo report for the functionalities?
Is it possible to create comment without using a template?

**Comment by rotda** [comment]
@ivanfemia you can test it with ZDEMO_EXCEL29  load a excel file with comments and then in created excel file there should be than the comments also. 

And no at the moment it copies only the comments from the template , there is no solution at the moment to create comments. It is also not so easy because in the vmldrawings file are the x y coordinates of the comments.

**Comment by AndreaBorgia-Abo** [comment]
#781 was merged and resulted in some conflicts, sorry for the inconvenience.

**Comment by sandraros** [comment]
@rotda This PR is mixing different topics, so I have created two distinct PRs containing your autofilter fixes (with tiny modifications) and concerning the comments (the feature named "notes" in latest Excel versions), I think the feature was introduced in parallel to your PR:
- #546 autofill fixed by #822 as per your indications
- #547 autofill fixed by #821 as per your indications
  - NB: #819 also concerned, fixed by #820
- #180 fixed by #583

I propose to close this PR when #546, #547 and #819 are closed. Thank you for your contribution! 👍 @AndreaBorgia-Abo fyi

**Pull request closed without merging**
