### PR TITLE
get INT8 typekind dynamic (+ minor PP)

### LINKED ISSUE #1064: SAP 740 install
Just installed the software on to SAP 740 system and am finding syntax errors does the system need to be 750?

Syntax error in ZCL_EXCEL_WORKSHEET method CONVERT_TO_TABLE field TYPEKIND_INT8 is unknown. A search on Google says that this type is defined in SAP 750.

Many thanks

### PR DESCRIPTION
**Pull request by bigld**
fixes #1064

### CODE REVIEW

**Review by larshp — APPROVED** [review]
looks good to me

**Comment by AndreaBorgia-Abo** [comment]
Can the PR be merged?

**Comment by larshp** [comment]
@bigld needs to update/rebase the branch

if https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork it can be done by maintainers

**Review by AndreaBorgia-Abo — APPROVED** [review]
LGTM

**Pull request merged**
