### PR TITLE
Second Attempt

### PR DESCRIPTION
**Pull request by hardyp**
I pulled down the code from the main branch so it was identical in my development system to the GitHub repository, added the new code in the one method, did NOT press the pretty print button and then closed the original pull request and tried to make a new pull request.
If anything this has made things worse.

### CODE REVIEW

**Comment by AndreaBorgia-Abo** [comment]
Are you using Eclipse or SE80 and friends?

**Comment by hardyp** [comment]
It was SE80. I take it this process only works in Eclipse?

**Comment by hardyp** [comment]
I have been talking to Lars Petersen, inventor of abapGit and he says to delete my fork and create a new one. I have to go now so I will do that tomorrow, and next time do the upload/download in Eclipse. Lars thinks that GitHub says there is a difference because there are differences between blank spaces and tabs. Maybe SE80 automatically inserts tabs or does not automatically insert tabs or whatever it is that Eclipse does.

**Comment by AndreaBorgia-Abo** [comment]
Yes, I've already seen [problems](https://github.com/abapGit/abapGit/issues/4810) when editing classes with SE80 in terms of unintended reformatting.
The short and sweet version is:
1. fork project
2. create feature branch in abapGit and switch to it
3. use Eclipse to edit the code
4. in abapGit check the diff looks acceptable before pushing it to your repo
5. if all is good, create a PR with an appropriate description

**Comment by hardyp** [comment]
Ok this fine day I created a new pull request called "third attempt" and that one is looking good. Therefore this pull request can be closed.

**Pull request closed without merging**
