### PR TITLE
SET_AREA/SET_AREA_FORMULA: set value or formula for whole area instead top/left only

### LINKED ISSUE #867: `SET_AREA` and `SET_AREA_FORMULA` don't set a value or formula for given area, only top left cell
I expect the following code to set a value in rows 1 and 2 from column 1 to column 10, and a formula in rows 3 and 4 from column 1 to column 10, but I get the value only at cell A1 and the formula only at cell A3; note that the methods `SET_AREA_HYPERLINK` and `SET_AREA_STYLE` are able to set a hyperlink or a style on the whole given area:
```
REPORT.
CONSTANTS: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = new zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_area(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 1
          ip_row_to       = 2
          ip_value        = 'Google' ).
  lo_worksheet->set_area_hyperlink(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 1
          ip_row_to       = 2
          ip_url          = 'https://www.google.com'
          ip_is_internal  = abap_false ).
  lo_worksheet->set_cell( ip_column = 1 ip_row = 3 ip_value = '' ). " workaround bug 866
  lo_worksheet->set_cell( ip_column = 2 ip_row = 3 ip_value = '' ).
  lo_worksheet->set_area_formula(
          ip_column_start = 'A'
          ip_column_end   = 'J'
          ip_row          = 3
          ip_row_to       = 4
          ip_formula      = '"hello"&" "&"world"' ).
  data(style) = lo_excel->add_new_style( ).
  style->fill->fgcolor-rgb = zcl_excel_style_color=>c_yellow.
  style->fill->filltype = zcl_excel_style_fill=>c_fill_solid.
  lo_worksheet->set_area_style(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 5
          ip_row_to       = 6
          ip_style        = style->get_guid( ) ).
  lcl_output=>output( lo_excel ).
```
Currently, it shows:
image

Expected:
image

NB: `set_area_formula` is setting only one cell, and this is also buggy if the cell is not previously initialized due to buggy `set_cell_formula` which is called (see #866).

### PR DESCRIPTION
**Pull request by sandraros**
Fix #867

### CODE REVIEW

**Comment by sandraros** [comment]
This PR can be reviewed only after #868 has been merged.
**IMPORTANT** I need your opinion! There is a possible regression of productive code using `SET_AREA` and `SET_AREA_FORMULA`, as developers might have considered the bug of setting only one cell value or formula as a feature. To avoid clients be angry after this fix, we could instead add an ugly parameter to make the two methods work by default as before (e.g. new parameter `ip_respect_area` as boolean type with default value `abap_false`).

**Comment by AndreaBorgia-Abo** [comment]
@sandraros I hope to have a couple of hours on thursday evening to look at this and the other PR but first one quick question: how long has this behaviour been in place? The longer the timeframe, the greater the likelihood your suggestion of the ugly parameter is inevitable. Tip: if you know the code snippet to check, then "git bisect" is your friend.
EDIT: this one on sunday, hopefully

**Comment by sandraros** [comment]
@AndreaBorgia-Abo It's issue #364 and PR #574 December 14th, 2018. 3 years is sufficient to me to say the ugly parameter is inevitable. What parameter name would you propose? I'm not fan of my own proposal. Tip: I use GitHub "blame" to see the history of changes.

**Comment by sandraros** [comment]
Another possibility is to create new methods. We should now use `SET_AREA_NEW` and `SET_AREA_FORMULA_NEW`. `SET_AREA` and `SET_AREA_FORMULA` should be considered deprecated.

EDIT: **solution of `SET_AREA_NEW` and `SET_AREA_FORMULA_NEW` is abandoned.**

Demo program with new proposal (latest commit):
```
REPORT.
CONSTANTS: gc_save_file_name TYPE string VALUE 'test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = new zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_area_new(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 1
          ip_row_to       = 2
          ip_value        = 'Google' ).
  lo_worksheet->set_area_hyperlink(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 1
          ip_row_to       = 2
          ip_url          = 'https://www.google.com'
          ip_is_internal  = abap_false ).
  lo_worksheet->set_cell( ip_column = 1 ip_row = 3 ip_value = '' ). " workaround bug 866
  lo_worksheet->set_cell( ip_column = 2 ip_row = 3 ip_value = '' ).
  lo_worksheet->set_area_formula_new(
          ip_column_start = 'A'
          ip_column_end   = 'J'
          ip_row          = 3
          ip_row_to       = 4
          ip_formula      = '"hello"&" "&"world"' ).
  data(style) = lo_excel->add_new_style( ).
  style->fill->fgcolor-rgb = zcl_excel_style_color=>c_yellow.
  style->fill->filltype = zcl_excel_style_fill=>c_fill_solid.
  lo_worksheet->set_area_style(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 5
          ip_row_to       = 6
          ip_style        = style->get_guid( ) ).
  lcl_output=>output( lo_excel ).
```
What do you prefer?

**Comment by AndreaBorgia-Abo** [comment]
I'm getting side-tracked by other issues and I still haven't had a chance to review this in detail but I already have a few words to say and did not want to let too much time go by: I'm not a big fan of "new" methods (since they end up outstaying their welcome and "new" isn't particularly informative), the optional parameter approach alone seemed much better to me.

Ideally, we'd fix the behaviour in the existing method, with the possibility of reverting back to the older broken functionality via the optional parameter and maybe even insert an intentional warning in the code to nudge the developers into just using the correct functionality by leaving the default value of the parameter in place.

Something like this:
CONSTANTS: c_area_whole type c value 'W', "whole"
                        c_area_topleft type c value 'T'. "top-left
METHOD set_area.
* other params...
!ip_area TYPE ... DEFAULT c_area_whole

then in the implementation itself, we add an invalid pragma to trigger a syntax warning and/or a comment explaining the issue.

Yet another option could be a cross between these two approaches: fix the existing method (no parameter, though) and add a companion method set_area_topleft.

Oh and... this might be the right time to start a BREAKINGCHANGES file or something to that effect :)

**Comment by sandraros** [comment]
As you initially said, I agree that the fix should not break productive programs. So default parameter should be `c_area_topleft`. Concerning the suffix `NEW`, maybe `2` would be better (same as Microsoft solution for Excel Object Model with `Range.Value2` to not break programs using`Range.Value`, and same for `Worksheets.Add2`). Anyway having two versions of the same method doesn't make me happy 😉.

I think of another solution: the current behavior of `set_area` and `set_area_formula` makes sense only if `ip_merge = abap_true`. So we might agree to set all the cells of the area if `ip_merge = abap_false`. The solution could still break productive code but now I better understand the code and I'm more confident now that there's much less risk to break. 
- Example with `ip_merge = abap_true`:
  ```abap
  DATA: gc_save_file_name TYPE string VALUE 'PR_869.xlsx'.
  INCLUDE zdemo_excel_outputopt_incl.
  START-OF-SELECTION.
    DATA(lo_excel) = NEW zcl_excel( ).
    DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
    lo_worksheet->set_area(
        ip_column_start = 1
        ip_column_end   = 2
        ip_row          = 1
        ip_row_to       = 2
        ip_value        = 'Hello world'
        ip_merge        = abap_true ).
    lcl_output=>output( lo_excel ).
    ```
I agree for defining a change log 😀. I propose to discuss in new #885.

**Comment by AndreaBorgia-Abo** [comment]
I like your new proposal using ip_merge, but I think I'll need either dedicated unit tests or a demo to exercise those corner cases in order to fully understand the changes. Next weekend, hopefully.

**Comment by sandraros** [comment]
I committed the change to consider `ip_merge` as I proposed in my last comment, and removed the "_NEW" methods.

I just see that the program `ZDEMO_EXCEL13` is deliberately demonstrating that only one cell is changed for the whole area when `ip_merge` is false. Here is the result before the change:
image

With the change I did, all the cells would be now filled with "Test area".

It makes me perplex that they felt important to show that only one cell was changed, and I don't understand why they decided that. I would think that it's best to take no risk, and add the optional parameter (i.e. !ip_area TYPE ty_area DEFAULT c_area_topleft`) so that there's no regression.

**Comment by AndreaBorgia-Abo** [comment]
Ok, after reviewing the bug, your sample code and demo 13, plus the generated files with Libreoffice and Excel, I agree that adding the new optional parameter defaulting to top-left only makes a ton of sense, go for it! The parameter should mention this discussion, briefly: "PR so and so for more details"
See if you can pretty print only those classes, by the way: it shouldn't generate too many spurious changes, as far as I can see.

**Comment by sandraros** [comment]
Thanks. Here's a new commit with below full demo program, with and without new parameter `IP_AREA`:
```abap
REPORT.
CONSTANTS: gc_save_file_name TYPE string VALUE 'PR_869.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = new zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_area(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 1
          ip_row_to       = 2
          ip_value        = 'Google' ).
  lo_worksheet->set_area_hyperlink(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 1
          ip_row_to       = 2
          ip_url          = 'https://www.google.com'
          ip_is_internal  = abap_false ).
  lo_worksheet->set_area_formula(
          ip_column_start = 'A'
          ip_column_end   = 'J'
          ip_row          = 3
          ip_row_to       = 4
          ip_formula      = '"hello"&" "&"world"' ).
  data(style) = lo_excel->add_new_style( ).
  style->fill->fgcolor-rgb = zcl_excel_style_color=>c_yellow.
  style->fill->filltype = zcl_excel_style_fill=>c_fill_solid.
  lo_worksheet->set_area_style(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 5
          ip_row_to       = 6
          ip_style        = style->get_guid( ) ).
  "-- NEW FEATURE --
  lo_worksheet->set_area(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 7
          ip_row_to       = 8
          ip_value        = 'Google'
          ip_area         = lo_worksheet->c_area-whole ).
  lo_worksheet->set_area_hyperlink(
          ip_column_start = 1
          ip_column_end   = 10
          ip_row          = 7
          ip_row_to       = 8
          ip_url          = 'https://www.google.com'
          ip_is_internal  = abap_false ).
  lo_worksheet->set_area_formula(
          ip_column_start = 'A'
          ip_column_end   = 'J'
          ip_row          = 9
          ip_row_to       = 10
          ip_formula      = '"hello"&" "&"world"'
          ip_area         = lo_worksheet->c_area-whole ).
  lcl_output=>output( lo_excel ).
```

**Review by AndreaBorgia-Abo — APPROVED** [review]
LGTM

**Pull request merged**
