### PR TITLE
Pretty print

### LINKED ISSUE #780: Harmonize pretty print settings
In the same principle as #773, different code uses different styles for keyword/identifier upper/lower case. 

Propose standardising on the most commonly used format of keyword upper / identifier lower case to minimise large diffs due to pretty print.

See also [Style Guides](https://github.com/SAP/styleguides/blob/main/clean-abap/sub-sections/UpperVsLowerCase.md) on the topic.

### PR DESCRIPTION
**Pull request by pokrakam**
Pretty print everything in keyword upper / identifier lower in one dedicated commit in order to avoid large diff problem 
Closes #780 if agreement to use this as a project standard.

Even if a different standard will be used in future, at least everything is in one format now.

### CODE REVIEW

**Comment by larshp** [comment]
@AndreaBorgia-Abo what would you like to do? if you review this one, it can be merged, but will probably cause conflicts in all open PRs

**Comment by AndreaBorgia-Abo** [comment]
@larshp I guess it can't be helped and I'm fine with a little extra work as long as this is once and for all. 
Perhaps we should first write the preferred settings in the coding guidelines (hello @sandraros ) and commit that PR, so that when we pull this one in we are able to reference the guidelines in all conflicting PRs and ask contributors for a little extra editing. All onboard with this?

**Comment by larshp** [comment]
and much of the pretty-printing can be enforced by the linter

**Comment by pokrakam** [comment]
Agree with @AndreaBorgia-Abo 
On a couple of random checks several open PRs already have conflicts.

**Comment by sandraros** [comment]
Agreed with all @AndreaBorgia-Abo @pokrakam @larshp : to add it to the coding guidelines first ; then update the linter settings ; and ask people to resolve PR conflicts or do it ourselves (like mines or #669 that I am currently reviewing)

**Comment by AndreaBorgia-Abo** [comment]
Very well, I'll have a look this evening

**Review by AndreaBorgia-Abo — APPROVED** [review]
Other than some funny new elements in demos/zdemo_excel_wda01.wdyn.xml it looks just as described: differences are either formatting-related or keyword lowercase to uppercase conversion and viceversa for identifiers.
Pulled the tree in my 7.52SP04 demo, all objects active, good.

**Pull request merged**
