### PR TITLE
enable 255 cell header with table binding

### LINKED ISSUE #726: Max width 40 for column headers of BIND_TABLE
The field catalog of method `BIND_TABLE` of class `ZCL_EXCEL_WORKSHEET` defines column headers of 10, 20 or 40 characters (components `SCRTEXT_M`, `SCRTEXT_S` and `SCRTEXT_M`, and method parameter `IV_DEFAULT_DESCR` to select the preferred width).

These limits make sense only with the ABAP Dictionary. In Excel, a column header may have up to 255 characters.

To define a text of more than 40 characters, the workaround is to call `SET_CELL` after `BIND_TABLE` to change the value of a column header.

Is it possible to extend the field catalog to have a new component with length 255 for containing extended column headers, so that to avoid initializing the table values at two places in the code?

Example program for column header with 40 characters:
```
DATA: gc_save_file_name TYPE string VALUE 'wider_table_header_text.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.
  SELECT carrid, carrname FROM scarr INTO TABLE @DATA(scarr) UP TO 1 ROWS.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  DATA(lt_field_catalog) = zcl_excel_common=>get_fieldcatalog( ip_table = scarr ).
  LOOP AT lt_field_catalog ASSIGNING FIELD-SYMBOL(<ls_field_catalog>).
    <ls_field_catalog>-scrtext_l = |this is the widest possible column text{ sy-tabix }|.
  ENDLOOP.
  lo_worksheet->bind_table(
    EXPORTING
      ip_table            = scarr
      it_field_catalog    = lt_field_catalog
      is_table_settings   = VALUE zexcel_s_table_settings(
                              table_name       = 'RR'
                              top_left_column  = 'A'
                              top_left_row     = 1
                              show_row_stripes = abap_true )
      iv_default_descr    = 'L' ).
  lcl_output=>output( cl_excel = lo_excel ).
```

### LINKED ISSUE #764: Overcome max width 40 for column headers of BIND_TABLE
With the method `bind_table`, the widest possible column header is 40 characters only. If trying to force a longer text with the method `set_cell`, there are two error popups when opening the Excel file:

Code to reproduce:
```abap
DATA: gc_save_file_name TYPE string VALUE 'wider_table_header_text.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.
  SELECT carrid, carrname FROM scarr INTO TABLE @DATA(scarr) UP TO 1 ROWS.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  DATA(lt_field_catalog) = zcl_excel_common=>get_fieldcatalog( ip_table = scarr ).
  LOOP AT lt_field_catalog ASSIGNING FIELD-SYMBOL(<ls_field_catalog>).
    <ls_field_catalog>-scrtext_l = |this is the widest possible column text{ sy-tabix }|.
  ENDLOOP.
  lo_worksheet->bind_table(
    EXPORTING
      ip_table            = scarr
      it_field_catalog    = lt_field_catalog
      is_table_settings   = VALUE zexcel_s_table_settings(
                              table_name       = 'RR'
                              top_left_column  = 'A'
                              top_left_row     = 1
                              show_row_stripes = abap_true )
      iv_default_descr    = 'L' ).
  lo_worksheet->set_cell(
      ip_column = 1
      ip_row    = 1
      ip_value  = |much longer text than permitted in the field catalog| ).
  lcl_output=>output( cl_excel = lo_excel ).
```

Actual result: there are these two error popups when opening the Excel file:
> "We found a problem with some content in 'xxxxx.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes." \
image
> If pressing Yes, there is another popup: "Repairs to 'xxxxx.xlsx' Excel was able to open the file by repairing or removing the unreadable content. Repaired Records: Table from /xl/tables/table1.xml part (Table) Click to view log file listing repairs <.xml file>" \
image
> and the repaired Excel file opens: \
image

Expected result:
- No repair needed, the column title set via `set_cell` is kept.

### PR DESCRIPTION
**Pull request by bigld**
Fixes #764
Closes #726

related to #970

### CODE REVIEW

**Comment by sandraros** [comment]
For information, many lines are changed, it's difficult to concentrate on the lines which only concern the fix. It would be better to provide two distinct PRs, one for the fix and one for the pretty printer. Thanks.

**Comment by sandraros** [comment]
Thanks a lot, I'll review it this week-end (unless Andrea takes it).

**Comment by sandraros** [comment]
I created a branch in the demos to make [ZDEMO_EXCEL47](https://github.com/abap2xlsx/demos/tree/sandraros/255-header) use your feature, but I can't make it work, the generated XLSX file is corrupted. Could you check what's going on?

**Comment by bigld** [comment]
there was an issue with the total function - it's fixed now

**Comment by lurki9** [comment]
@bigld thanks for this, was just about to figure this out myself but figured I would search in case someone else was working on it. :D

**Review by sandraros — APPROVED** [review]
LGTM 👍

**Pull request merged**
