### PR TITLE
Update zcl_excel_worksheet.clas.testclasses.abap

### PR DESCRIPTION
**Pull request by rplantiko**
Replacing IF_ABAP_UNIT_CONSTANT by IF_AUNIT_CONSTANTS, as proposed by @sandraros

### CODE REVIEW

**Comment by rplantiko** [comment]
This pull request contains all the changes of the PR #1079 (closed by me without being merged), plus the change proposed by @sandraros (Using IF_AUNIT_CONSTANTS instead of IF_ABAP_UNIT_CONSTANT).

**Review by sandraros — APPROVED** [review]
LGTM. Thanks, merging! 👍

**Comment by sandraros** [comment]
Fix #1072

**Comment by AndreaBorgia-Abo** [comment]
Whoopsie, this QUIT-NO constant does not exist on 731 :(

**Pull request merged**
