### PR TITLE
solves part of #859 - split tests for convert_column2int

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**

### CODE REVIEW

**Review by AndreaBorgia-Abo — COMMENTED** [review]
changes are as expected

**Comment by larshp** [comment]
@AndreaBorgia-Abo is this PR ready for review? the title says "WIP"

if its work in progress, suggest converting to draft pull request. If ready for review, removing the "WIP" from title

**Comment by AndreaBorgia-Abo** [comment]
It is WIP because this does NOT by itself address the whole of #859 . Same logic as for the DDIC cleanups.
Be as it may, this use of WIP by me is creating confusion so I'll have to find another way to encode partial solutions to long running issues. Any suggestions? I could either leave it out altogether and avoid "fix" or .... what else?

**Comment by larshp** [comment]
just reference it in the description eg. "this PR solves first part of #859"

**Review by larshp — APPROVED** [review]
looks good to me, thanks 👍

**Pull request merged**
