### PR TITLE
force offline mode if not in background

### PR DESCRIPTION
**Pull request by bigld**
I think this will do the trick without "dirty hack"

### CODE REVIEW

**Comment by sandraros** [comment]
Does it fix #1097?

**Comment by bigld** [comment]
fixes #1097

**Comment by sandraros** [comment]
Thanks. I'll try to test and merge before this week-end.

**Comment by sandraros** [comment]
It's difficult to understand the new code `IF sy-batch = abap_true AND io_salv->is_offline( ) = abap_false` whose result is always false (I guess).

I did these tests, the test 1 fails with ABAP 7.52 SP 0, it ignores the layout changed by the user (need to run `io_salv->get_metadata( )` to get the changed layout):
1. Display ALV, layout manually changed, then run abap2xlsx conversion
2. Prepare without displaying ALV, run abap2xlsx conversion
3. ALV data intercepted without displaying ALV, without any ALV default variant, then run abap2xlsx conversion
4. ALV data intercepted without displaying ALV, with an ALV default variant, then run abap2xlsx conversion
5. Run in background the tests 2 to 4

I have proposed another solution via the PR #1109 (waiting for abaplint fix https://github.com/abaplint/deps/pull/198 /cross check still running). It works both in ABAP 7.52 and ABAP 7.57.

Please tell me your view on that?

**Comment by bigld** [comment]
perfect solution with #1109

**Pull request closed without merging**
