### PR TITLE
Add exeption handling

### LINKED ISSUE #606: Exception Handling Missing
Code Inspection checks fail as throughout the code, exceptions are declared and not caught.

### PR DESCRIPTION
**Pull request by pokrakam**
Closes #606

### CODE REVIEW

**Comment by pokrakam** [comment]
@larshp Could you please check linter message? Does this really not exist or a parser error or a misleading message? I don't have an old system to check with.

**Comment by larshp** [comment]
I think the findings are correct, extract the method call to a variable, but I also dont have a 702 system to test on

**Comment by pokrakam** [comment]
> I think the findings are correct, extract the method call to a variable, but I also dont have a 702 system to test on

You're right, didn't even occur to me. Updated. Thanks!

**Review by sandraros — APPROVED** [review]
Thanks. I just added the 2 first commits so that to keep only changes relevant to exception handling, so that I can find out only the exact changes. We can do another pull request to reapply pretty printer (2nd commit).

The [3rd commit](https://github.com/sapmentors/abap2xlsx/pull/889/commits/6000c62099d0006be993a10484114e4b38ba5f10) is about few proposals, please confirm if it's okay for you then we can "squash and merge":
1. a few alignment fixes
2. ls_message renamed to lv_message
3. message ... type 'E' -> message ... type 'I' display like 'E' to avoid short dumps in demo programs

**Comment by pokrakam** [comment]
@sandraros Thanks, well spotted with the message type E, I originally declared the exception in the FORM to pass it up, but for some reason that escapes me at the moment it turned out a bad idea and I moved the exception handling into the form. OK to merge as is.

**Pull request merged**
