### PR TITLE
Delete objects moved to abap2xlsx/demos repository

### PR DESCRIPTION
**Pull request by sandraros**
As discussed in #861, proposing to remove the demo programs from the main repository. I have just created the repository https://github.com/abap2xlsx/demos with all the demo programs. Hopefully it will also solve #993 (complex issue related to abapGit way of pulling and combination of DDIC, programs, classes and transformations).

### CODE REVIEW

**Review by AndreaBorgia-Abo — APPROVED** [review]
LGTM
One question, though: the [linter complaints](https://github.com/abap2xlsx/demos/runs/5438904066) are due to the move, right?

**Comment by sandraros** [comment]
I didn't see that. I have added `abaplint.json` and changed the rules a little bit, compared to abap2xlsx/abap2xlsx. Now it's fine.

**Comment by AndreaBorgia-Abo** [comment]
@sandraros do we want to move the W3MI objects as well? This is not needed for the abapGit issue but the subpackage is not otherwise used.

**Comment by sandraros** [comment]
@AndreaBorgia-Abo Oh yes, sure, I forgot them!

**Comment by AndreaBorgia-Abo** [comment]
Moving season.... PRs incoming....
@sandraros I can't assign [the PR](https://github.com/abap2xlsx/demos/pull/1) to you under "demos", weird.
The [other one](https://github.com/abap2xlsx/abap2xlsx/pull/1009) was fine.

**Pull request merged**
