### PR TITLE
Unicode characters not written to excel

### LINKED ISSUE #672: Missing Vietnamese text when output
Hi,
I was exported  a demo excel sheet from ZDEMO_EXCEL1 with Vietnamese's character like 'ắ' or 'ớ'.
But character was missing when output.
How to solve this problem?
Please suggest me,
Thank you.
Code in program:
image
Output:
image

### PR DESCRIPTION
**Pull request by sandraros**
Fix #672 ("vietnamese") and #688 ("emoji").
It works for a recent system but unfortunately I can't test it on a old system to make sure that the new method `is_support_non_xml_characters` returns false.

### CODE REVIEW

**Comment by gregorwolf** [comment]
Can you extend or provide a test report to replicate this behaviour?

**Comment by sandraros** [comment]
I propose to extend the Hello world program ZDEMO_EXCEL1 to write "Hello world" in [10 most-spoken languages in the world](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers) + emoji 👋🌎, 👋🌍, 👋🌏 (waving hand + 3 parts of the world).

**Comment by gregorwolf** [comment]
Good suggestion. Please add it to this PR.

**Comment by sandraros** [comment]
Done.

**Comment by AndreaBorgia-Abo** [comment]
@sandraros how old should the system be?
Would SAP_ABA SAPKA74003 be enough?

**Comment by sandraros** [comment]
@AndreaBorgia-Abo I tested on a 7.52 system so 7.40 is fine.

**Comment by AndreaBorgia-Abo** [comment]
Ok, it returns false and the content of the test string is: 3C3F786D6C2076657273696F6E3D22312E30223F3E3C524F4F543EEDA080EDB0803C2F524F4F543E

unicodetest

The generated Excel looks like this:
2021-05-19 20_06_59-abap2xlsx Demo_ Hello World

**Comment by sandraros** [comment]
@AndreaBorgia-Abo I guess Excel doesn't say the file is corrupted. Could you force r_result = abap_true to see what happens?

**Comment by AndreaBorgia-Abo** [comment]
With abap_false, the file is displayed, no warnings or anything: it just works.
Forcing abap_true on our system, I get the folowing messages:
1.
2021-05-20 09_43_16-Microsoft Excel
2.
2021-05-20 09_46_39-Ripristini a '~SAP{B7EF7487-7E8E-407B-A568-FE6CEF73FA98} xlsx'

**Comment by sandraros** [comment]
@AndreaBorgia-Abo So, that was the perfect test with SAP kernel having the bug, and correctly detected by abap2xlsx and handled the best way it can. Thanks!

**Comment by AndreaBorgia-Abo** [comment]
Any particular notes to check or kernel version?

**Comment by sandraros** [comment]
@AndreaBorgia-Abo SKIP_NON_XML_CHARACTERS was made available in [note 1750204](https://launchpad.support.sap.com/#/notes/1750204) and Kernel must be as per [note 2220720](https://launchpad.support.sap.com/#/notes/2220720).

**Comment by AndreaBorgia-Abo** [comment]
1750204: SAP_BASIS is SAPKB74003, higher than required
2220720: Kernel is 749 PL 500, also higher.
This should be ok, right?

**Comment by sandraros** [comment]
@AndreaBorgia-Abo Your system should have valid support for "non-XML characters" according to the SAP notes, but the method says your SAP system doesn't support them, and the test you did by forcing true via debug confirms it. What value do you get in `lv_xstring` please?

**Comment by AndreaBorgia-Abo** [comment]
3C3F786D6C2076657273696F6E3D22312E30223F3E3C524F4F543EEDA080EDB0803C2F524F4F543E

**Comment by sandraros** [comment]
@AndreaBorgia-Abo Well, EDA080 and EDB080 correspond to invalid UTF-8 conversion of the two (invalid) code points U+D800 and U+DC00, but if the SAP kernel supports it correctly, it should return F0908080 (as on my 7.52 system), which corresponds to the UTF-8 code value of character U+10000. I don't know what to think. Maybe UCCP doesn't work well for surrogate code points U+D800 and U+DC00 in old systems. I have `lv_u10000` hexadecimal value '00D800DC', and my system Code Page 4103/Little Endian (transaction code SNLS). What do you have?

**Comment by AndreaBorgia-Abo** [comment]
immagine

immagine

I think I could copypaste the method body into a standalone report and run it across a few systems, without bothering with the rest of abap2xlsx, then write down SAP_ABA and SAP_BASIS plus the contents of those variables. Deal?

**Comment by sandraros** [comment]
@AndreaBorgia-Abo The current code does what I expect it to do, but I didn't expect that it wouldn't work in your system configuration. I think I have just found out why, maybe that doesn't work in any version before 7.52, that's explained in the [note 2922674 - Support for Unicode Characters U+10000 to U+10FFFF in the iXML kernel library / ABAP package SIXML](https://launchpad.support.sap.com/#/notes/2922674). Hence, maybe this completely [new code](https://github.com/sandraros/abap2xlsx/tree/New-solution-instead-of-PR-%23743) might be more universal. Could you test it please?

**Comment by AndreaBorgia-Abo** [comment]
The new code works :)
immagine

**Comment by gregorwolf** [comment]
Thanks a lot.

**Comment by AndreaBorgia-Abo** [comment]
@gregorwolf [my comment](https://github.com/sapmentors/abap2xlsx/pull/743#issuecomment-846102799) refers to an [out-of-PR version](https://github.com/sandraros/abap2xlsx/tree/New-solution-instead-of-PR-%23743) that @sandraros wanted me to test, I believe, before including it in the PR. As the master branch stands now, those changes are not yet present.

**Comment by gregorwolf** [comment]
Sorry. Do you have already a PR for the improvements?

**Comment by AndreaBorgia-Abo** [comment]
Let's wait for @sandraros , it's her code and her PR.

**Comment by sandraros** [comment]
@AndreaBorgia-Abo Sorry for the delay. I just created the bug #756 that corresponds to the symptom you have seen in 7.40, and the PR #757, that does the same solution as you have tested but the code is a little bit different so that --I hope-- there's less risk of error in non-Unicode systems (+ comments). Could you test this new PR please?

**Comment by AndreaBorgia-Abo** [comment]
@sandraros the system is isolated so I copied the [whole class](https://raw.githubusercontent.com/sapmentors/abap2xlsx/9838ebcbe4f74d46e6bdfdc22b39c9361d6fc5d6/src/zcl_excel_writer_2007.clas.abap) from the PR, verified it has the new "Excerpt from Note" block and ran the same demo: below is the output as shown my LibreOffice on my Linux desktop.
immagine
Looks good to me.

**Pull request merged**
