### PR TITLE
How to get rid of the obscure code in writer's method create_xl_sheet_sheet_data step #1

### LINKED ISSUE #440: Autofilter with more values does not work
**EDIT 2024 by @sandraros: I have added a [comment below](https://github.com/abap2xlsx/abap2xlsx/issues/440#issuecomment-2156021645) to fully describe and reproduce the bug.**

Hi, 

I have defined autofilter for 13th row. And I want to set more values to first column. I do it by:

```

lv_cell_value = 'Sum'.

  lo_autofilter->set_value(
    exporting
      i_column = 1    " Cell Column
      i_value  = lv_cell_value
  ).

  lv_cell_value = 'ProjectA'.

  lo_autofilter->set_value(
    exporting
      i_column = 1    " Cell Column
      i_value  = lv_cell_value
  ).

  lv_cell_value = 'ProjectB'.

  lo_autofilter->set_value(
    exporting
      i_column = 1    " Cell Column
      i_value  = lv_cell_value    " Cell Column
  ).

  lv_cell_value = 'ProjectC'.

  lo_autofilter->set_value(
    exporting
      i_column = 1    " Cell Column
      i_value  = lv_cell_value   " Cell Column
  ).
```

When excel is generated, the values in filter are selected, but they are not displayed. I have to open the filter, the values are checked but I have to press 'OK' in order to 'apply' the filter.

I'm doing this because I want all values to be selected when excel is generated. But when I just set filter without setting values then nothing is selected in the filter.

I have added one value to report `ZDEMO_EXCEL33` and the result is the same. All values defined in code are checked in the filter but you must press 'OK' to apply the filter. Could you please help me with that? Thank you in advance.

### PR DESCRIPTION
**Pull request by darnoc312**
closes #440 and is the first step of #1230 (not yet closed)

As described in discussions #1229 the current autofilter finds only the first value of each filter column (1st bug)
and then shows the line independent from all other filter columns (2nd bug).

This is the demo program (similar to ZDEMO_EXCEL33) containing data for 4 clients and
an autofilter for clients 001 and 002 and country BE and DE in that order.

```abap
REPORT  zdemo_excel33_test.

TYPES: BEGIN OF ty_t005t_line,
         mandt   TYPE mandt,
         spras   TYPE spras,
         land1   TYPE land1,
         landx   TYPE landx,
         natio   TYPE natio,
         landx50 TYPE landx50,
         natio50 TYPE natio50,
       END OF ty_t005t_line,
       ty_t005t_lines TYPE TABLE OF ty_t005t_line.

DATA: lo_excel      TYPE REF TO zcl_excel,
      lo_worksheet  TYPE REF TO zcl_excel_worksheet,
      lo_converter  TYPE REF TO zcl_excel_converter,
      lo_autofilter TYPE REF TO zcl_excel_autofilter.

DATA lt_test TYPE ty_t005t_lines.

DATA: l_cell_value TYPE zexcel_cell_value,
      ls_area      TYPE zexcel_s_autofilter_area.
DATA: ls_option TYPE zexcel_s_converter_option.

CONSTANTS: gc_save_file_name TYPE string VALUE '33_autofilter.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

PARAMETERS p_convex AS CHECKBOX.

START-OF-SELECTION.

  " Creates active sheet
  CREATE OBJECT lo_excel.

  " Get active sheet
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_title( ip_title = 'Internal table' ).

  PERFORM load_fixed_data CHANGING lt_test.

  CREATE OBJECT lo_converter.

  ls_option-conv_exit_length = p_convex.
* lo_converter->set_option( ls_option ).
  lo_converter->convert( EXPORTING
                            is_option    = ls_option    "use ls_option here
                            it_table     = lt_test
                            i_row_int    = 1
                            i_column_int = 1
                            io_worksheet = lo_worksheet
                         CHANGING
                            co_excel     = lo_excel ) .
  PERFORM set_column_headers USING lo_worksheet 'Client;Language;Country;Name;Nationality;Long name;Nationality'.

  lo_autofilter = lo_excel->add_new_autofilter( io_sheet = lo_worksheet ) .

  ls_area-row_start = 1.
  ls_area-col_start = 1.
  ls_area-row_end = lo_worksheet->get_highest_row( ).
  ls_area-col_end = lo_worksheet->get_highest_column( ).

  lo_autofilter->set_filter_area( is_area = ls_area ).

*  lo_worksheet->get_cell( EXPORTING
*                             ip_column    = 'C'
*                             ip_row       = 2
*                          IMPORTING
*                             ep_value     = l_cell_value ).
*  lo_autofilter->set_value( i_column = 3
*                            i_value  = l_cell_value ).
  lo_autofilter->set_value( i_column = 1
                            i_value  = '001' ).
  lo_autofilter->set_value( i_column = 1
                            i_value  = '002' ).
  lo_autofilter->set_value( i_column = 3
                            i_value  = 'BE' ).
  lo_autofilter->set_value( i_column = 3
                            i_value  = 'DE' ).


*** Create output
  lcl_output=>output( lo_excel ).


*&---------------------------------------------------------------------*
*&      Form  load_fixed_data
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->CT_TEST    text
*----------------------------------------------------------------------*
FORM load_fixed_data CHANGING ct_test TYPE ty_t005t_lines.
  DATA: lt_lines  TYPE TABLE OF string,
        lv_line   TYPE string,
        lt_fields TYPE TABLE OF string,
        lv_comp   TYPE i,
        lv_field  TYPE string,
        ls_test   TYPE t005t.
  FIELD-SYMBOLS: <lv_field> TYPE simple.

  APPEND '001 E AD Andorra    Andorran    Andorra    Andorran   ' TO lt_lines.
  APPEND '001 E BE Belgium    Belgian     Belgium    Belgian    ' TO lt_lines.
  APPEND '001 E DE Germany    German      Germany    German     ' TO lt_lines.
  APPEND '001 E FM Micronesia Micronesian Micronesia Micronesian' TO lt_lines.
  APPEND '002 E AD Andorra    Andorran    Andorra    Andorran   ' TO lt_lines.
  APPEND '002 E BE Belgium    Belgian     Belgium    Belgian    ' TO lt_lines.
  APPEND '002 E DE Germany    German      Germany    German     ' TO lt_lines.
  APPEND '002 E FM Micronesia Micronesian Micronesia Micronesian' TO lt_lines.
  APPEND '003 E AD Andorra    Andorran    Andorra    Andorran   ' TO lt_lines.
  APPEND '003 E BE Belgium    Belgian     Belgium    Belgian    ' TO lt_lines.
  APPEND '003 E DE Germany    German      Germany    German     ' TO lt_lines.
  APPEND '003 E FM Micronesia Micronesian Micronesia Micronesian' TO lt_lines.
  APPEND '004 E AD Andorra    Andorran    Andorra    Andorran   ' TO lt_lines.
  APPEND '004 E BE Belgium    Belgian     Belgium    Belgian    ' TO lt_lines.
  APPEND '004 E DE Germany    German      Germany    German     ' TO lt_lines.
  APPEND '004 E FM Micronesia Micronesian Micronesia Micronesian' TO lt_lines.
  LOOP AT lt_lines INTO lv_line.
    CONDENSE lv_line.
    SPLIT lv_line AT space INTO TABLE lt_fields.
    lv_comp = 1.
    LOOP AT lt_fields INTO lv_field.
      ASSIGN COMPONENT lv_comp OF STRUCTURE ls_test TO <lv_field>.
      <lv_field> = lv_field.
      lv_comp = lv_comp + 1.
    ENDLOOP.
    APPEND ls_test TO ct_test.
  ENDLOOP.
ENDFORM.                    "load_fixed_data

*&---------------------------------------------------------------------*
*&      Form  set_column_headers
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->IO_WORKSHEET  text
*      -->IV_HEADERS    text
*      -->RAISING       text
*      -->ZCX_EXCEL     text
*----------------------------------------------------------------------*
FORM set_column_headers
    USING io_worksheet TYPE REF TO zcl_excel_worksheet
          iv_headers   TYPE csequence
    RAISING zcx_excel.

  DATA: lt_headers TYPE TABLE OF string,
        lv_header  TYPE string,
        lv_tabix   TYPE i.

  SPLIT iv_headers AT ';' INTO TABLE lt_headers.
  LOOP AT lt_headers INTO lv_header.
    lv_tabix = sy-tabix.
    io_worksheet->set_cell( ip_row = 1 ip_column = lv_tabix ip_value = lv_header ).
  ENDLOOP.

ENDFORM.                    "set_column_headers
```

The following attachment contains the wrong result:
Lines 2-5 are shown because of 001 (first value for client) independent from filter values for country.
Lines 3,7,11,15 are shown because of BE (first value for country) independent from filter values for client.
Line 3 is a mix of both.
[33_autofilter_wrong.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/15469001/33_autofilter_wrong.xlsx)

And this is the result after the fix:
[33_autofilter_ok.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/15469011/33_autofilter_ok.xlsx)

### CODE REVIEW

**Comment by sandraros** [comment]
Thanks a lot. Just to keep focused, for now I'd like a PR to fix #440 only: if I'm not wrong, only the below lines are needed to fix the bug (the other lines are code improvement that I would like to be in another PR):
https://github.com/abap2xlsx/abap2xlsx/blob/1bb354a138a29f7dfe1f4d5d8eee59d63b50435c/src/zcl_excel_writer_2007.clas.abap#L4399-L4400
https://github.com/abap2xlsx/abap2xlsx/blob/1bb354a138a29f7dfe1f4d5d8eee59d63b50435c/src/zcl_excel_writer_2007.clas.abap#L4579-L4580
Also, `l_autofilter_hidden`, `lt_values` and `ls_values` are not used anymore, so I'd like to have them removed everywhere.

You may create another PR for improving the code of `is_row_hidden` and I'll review it.

**Comment by darnoc312** [comment]
This is not only a 'nice to have' improvement.
The autofilter's method get_filter_column should only be called if you really want to add values, because this filter column will be created if it is not existing.
You find a call like this in autofilter's method set_value. This method sets a rule and adds a value afterwards.

For an example use the following program to set filter values for CONNID (Column C) and AGENCYNUM (Column S).
This creates two filter columns.

```abap
REPORT zdemo_excel33_test2.

DATA: lt_bookings TYPE TABLE OF sbook,
      ls_area     TYPE zexcel_s_autofilter_area.

DATA: lo_excel      TYPE REF TO zcl_excel,
      lo_worksheet  TYPE REF TO zcl_excel_worksheet,
      lo_autofilter TYPE REF TO zcl_excel_autofilter.

CONSTANTS: gc_save_file_name TYPE string VALUE '33_autofilter_test.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.


START-OF-SELECTION.

  " Creates active sheet
  CREATE OBJECT lo_excel.

  " Get active sheet
  lo_worksheet = lo_excel->get_active_worksheet( ).
  lo_worksheet->set_title( ip_title = 'SBOOK table' ).

  SELECT * FROM sbook INTO TABLE lt_bookings UP TO 1000 ROWS.

  lo_worksheet->set_table(
    EXPORTING
      ip_table           = lt_bookings
      ip_top_left_column = 'A'
      ip_top_left_row    = 1 ).

  lo_autofilter = lo_excel->add_new_autofilter( io_sheet = lo_worksheet ) .

  ls_area-row_start = 1.
  ls_area-col_start = 1.
  ls_area-row_end = lo_worksheet->get_highest_row( ).
  ls_area-col_end = lo_worksheet->get_highest_column( ).

  lo_autofilter->set_filter_area( is_area = ls_area ).

  lo_autofilter->set_value( i_column = 3          "'C'
                            i_value  = '0017' ).
  lo_autofilter->set_value( i_column = 19         "'S'
                            i_value  = '00000111' ).


*** Create output
  lcl_output=>output( lo_excel ).
```

In the old process then there are always two filter columns even until the call of get_values in writer's add_autofilter (local class).
At least that works.

In the new process the following would happen without my suggested change:
You know: The method is_row_hidden is called by every row in autofilter area.
The call by the first row creates 15 unnecessary filter columns for column D to R without rule and values.
Then every further call of is_row_hidden (here 999 times) has to loop over 17 instead of 2 filter columns.
This works because the 15 columns are skipped every time. But why we should create them anyway ?
Leaving the code unchanged doesn't give you any safety about any compatibility reasons, because the code was never used before.



Point 2: I agree. I suggested this already in #1229, too. Changed in this PR.

**Comment by sandraros** [comment]
So, this PR is now to fix #440 only? Stay focused please.

**Comment by darnoc312** [comment]
Sorry, changed it above again. I guess that is what you mean.

**Review by sandraros — APPROVED** [review]
Thanks, all good.

**Pull request merged**
