### PR TITLE
don't run SALV get_metadata if not displayed yet

### LINKED ISSUE #1097: Converter does not work if Grid not yet displayed
In online mode I would like to send the email before the ALV grid is displayed in the GUI.

I have a dirty trick to make this work as follows:

```ABAP
METHOD create_spreadsheet.
    "Convert SALV object into excel
    DATA: l_ws TYPE c LENGTH 10 VALUE 'ITS'.

    "If we do this (call the convertor) in the foreground we get a dump unless we do a dirty trick
    IF sy-batch EQ abap_false.
      EXPORT l_ws = l_ws TO MEMORY ID 'WWW_ALV_ITS'.
    ENDIF.

    DATA(converter) = NEW zcl_excel_converter( ).

    TRY.
        IF mo_alv IS BOUND.
          converter->convert(
            EXPORTING
              io_alv        = mo_alv
              it_table      = it_table[]
              i_table       = abap_true "Create as Table
              i_style_table = zcl_excel_table=>builtinstyle_medium2
            CHANGING
              co_excel      = mo_excel ).
        ELSE.
          RETURN.
        ENDIF.

        FREE MEMORY ID 'WWW_ALV_ITS'.

      CATCH zcx_excel INTO DATA(exception).
        DATA(message) = exception->get_text( ).
        MESSAGE message TYPE 'I'.
    ENDTRY.

  ENDMETHOD.
```

I was wondering if my "dirty trick" could somehow be embedded inside the converter class, so it does not matter in which order the conversion and the display of the ALV object happens.

Cheersy Cheers

Paul

### PR DESCRIPTION
**Pull request by sandraros**
fix #1097

### CODE REVIEW

**Comment by larshp** [comment]
suggest moving the class into the `not_could` folder

**Comment by sandraros** [comment]
Thanks for your vigilance, I moved the class to the `not_cloud` folder.

**Comment by sandraros** [comment]
NB: the fix had to consider these facts:
- in ABAP 7.52, `cl_salv_table` inherits from `cl_salv_model` this way it's possible to know if `get_metadata` can be called or not (callable if `salv_table->r_controller->r_adapter` is instantiated i.e. ALV is displayed),
- in ABAP 7.57, `cl_salv_table` doesn't inherit anything so impossible to do the same test, but hopefully `get_metadata` can be called always, even before the ALV is displayed.

**Review by AndreaBorgia-Abo — APPROVED** [review]
Tested on NPL (7.52SP04) and A4H (HANA1909) MiniSAPs with minimal sample program from @hardyp : problem can be reproduced and PR fixes it. Plus fix is short and to the point :)

**Pull request merged**
