### PR TITLE
Change package assignment of demo reports

### LINKED ISSUE #695: package structure
Hi,
Suggest moving all demo programs to a new package `/src/demo`, and core classes to `/src/core`

### PR DESCRIPTION
**Pull request by bigld**
closes #695 

only move demo reports to subpackage so one can pull "core" only with _Ignore Subpackages_

### CODE REVIEW

**Review by gregorwolf — APPROVED** [review]
LGTM

**Comment by WouterTriesCoding** [comment]
@gregorwolf  @bigld can we also change the package for the Webdynpro demo's? E.g. ZDEMO_EXCEL_WDA01

**Comment by larshp** [comment]
@WouterPeeters yea, pull requests welcome

**Comment by bigld** [comment]
here we go: #702 ;)

**Pull request merged**
