### PR TITLE
fix code template generation to work on 731

### LINKED ISSUE #1077: ZEXCEL_TEMPLATE_GET_TYPES does not run on 731
On SAP_ABA SAPKA73105, class CL_DEMO_OUTPUT does not have a NEW method and ZEXCEL_TEMPLATE_GET_TYPES cannot be activated (introduced in #669)
Then I went looking for a minimum required version in the documentation (a bit like abapGit starting from 702) and could not find it.

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**
fixes #1077

### CODE REVIEW

**Comment by AndreaBorgia-Abo** [comment]
leaving as draft because:
1. this is untested on 731
2. I intend to hijack this branch to deploy a dirty fix for #1085 for a presentation, then I'll split it into its branch later

**Comment by AndreaBorgia-Abo** [comment]
Of course it didn't work since:
1. cl_demo_output=>set_mode does not exist yet
2. cl_demo_output=>display has no parameters
Rewrote it, now it works.... commit incoming.

**Review by AndreaBorgia-Abo — COMMENTED** [review]
changes are as expected
(please squash the commits, makes no sense to pollute the log)

**Review by sandraros — APPROVED** [review]
LGTM, thanks! 👍

**Pull request merged**
