### PR TITLE
Redefinition Header Footer Image

### PR DESCRIPTION
**Pull request by mfallen**
Get errors when using header/footer in more than one sheet

### CODE REVIEW

**Comment by gregorwolf** [comment]
Can you try to have less differences in zcl_excel_worksheet.clas.abap? There where a lot of spaces removed or added.

**Comment by mfallen** [comment]
Hi @gregorwolf , looks like in the original coding there are "too much" spaces?

**Comment by gregorwolf** [comment]
Perhaps we could be really radical and do a pretty print with keywords uppercase, variables lowercase in the code based class editor.

**Comment by larshp** [comment]
pretty print keywords upper in class based editor is also what we do in abapGit, plus it can be automatically enforced via abaplint

**Comment by mfallen** [comment]
@gregorwolf  @larshp  Done, "pretty printed" the class

**Comment by gregorwolf** [comment]
Thanks.

**Pull request merged**
