### PR TITLE
start unit testing setup

### PR DESCRIPTION
**Pull request by larshp**
* few fcat structures moved to not_cloud package
* run few unit tests via open-abap and github actions
* `test/run.mjs` generates the file shown in https://abap2xlsx.github.io/abap2xlsx-web/

after this PR is merged, I'll add an ABAP editor to https://abap2xlsx.github.io/abap2xlsx-web/, and make it possible to click "run"

### CODE REVIEW

**Comment by larshp** [comment]
github is buggy today, hence the changing of draft status

**Comment by larshp** [comment]
only 2 files in /src/ moved, other changes doesnt impact installs, so this should be good to merge?

**Comment by larshp** [comment]
ready for review

**Comment by larshp** [comment]
I suggest prioritizing getting this PR merged, so we can start doing some automated testing, instead of doing only manual

**Comment by sandraros** [comment]
I don't know how to test this, can anyone else take it? Or any link which explains how to test it?

**Comment by larshp** [comment]
* in `src`, only 2 files moved, so there is no impact to installations other than this
* a few unit tests are run via transpiling, the result can be seen at https://github.com/abap2xlsx/abap2xlsx/actions/runs/6774261257/job/18410937004?pr=872, few notes in https://blogs.sap.com/2021/08/12/running-abap-unit-tests-on-github-actions/
* the check is not required, so the status can be anything
* I'll nurse it until it gets stable

**Comment by larshp** [comment]
I'm gonna merge this before getting into more merge conflicts

note: there are no changes to any files in `/src/`

**Pull request merged**
