### PR TITLE
Update zcl_excel_converter.clas.abap

### PR DESCRIPTION
**Pull request by K-Wagner**
Converting an ALV table that includes a color column failed because deep tables are not supported. The check that was addes prevents an error.

### CODE REVIEW

**Comment by gregorwolf** [comment]
Hi @K-Wagner,
is there any sample report that could be adjusted to replicate this issue first and then use your correction?

**Comment by K-Wagner** [comment]
I've tried to reproduce the error using ZDEMO_EXCEL32. When run interactively the color column is excluded in ZCL_EXCEL_COMMON~DESCRIBE_STRUCTURE, no problem there. I recalled I wanted to reproduce Excel files in batch mode also using an ALV Layout. There the problem begins. I enhanced ZDEMO_EXCEL32 to produce the output also when called from ZDEMO_EXCEL. Right now the color information is missing. Also there is made no column selection based on an ALV layout. Working on that.

**Comment by AndreaBorgia-Abo** [comment]
#781 was merged and resulted in some conflicts, sorry for the inconvenience.

**Comment by sandraros** [comment]
Hi @K-Wagner. I tried to reproduce but couldn't understand what problem you exactly faced. If I run the demo program you have proposed, I don't see any failure. The catalog returned by SALV in my 7.52 version doesn't contain the `COLOR_CELL` table type component you have added to contain the colors of cells. To continue the discussion, could you create an issue with details about how to reproduce? Thank you.

**Comment by sandraros** [comment]
I propose to close this PR for now. If there is still an issue, I propose that first an issue is opened which describes the exact reproduction steps. Thank you.

For history, here's what I obtain when I run the adapted version of ZDEMO_EXCEL32 provided in this PR after I click the button "Excel converter":
image

**Pull request closed without merging**
