### PR TITLE
Gradient Fill -> writer + demo programs 2 & 34

### PR DESCRIPTION
**Pull request by fidley**
I had some problem with loading last daily nugg of project, when I did it I had in code a lot of syntax errors with double key word" endmethod". Once I've removed duplicates I could add the proper coding for writer. For the reader I would need to spend some free time in next days to change it.

Chess looks like in 3D now :)

image

### CODE REVIEW

**Comment by review-ninja** [comment]
[ReviewNinja](http://app.review.ninja/ivanfemia/abap2xlsx/pull/350)

**Comment by ivanfemia** [comment]
Hi Łukasz,

are you using the latest SAPLink version at www.saplink.org? are you also using the Preatty Printer with the Keyword uppercase setup, this would remove a lot of dummy changes? 
There are so many changes that GitHub notifies me some conflicts that I have to double check.
the excel looks really cool.

Thank you
Ivan

**Comment by fidley** [comment]
Hi Ivan, 
yes, I've downloaded last version of SAPLink and last daily build of A2X. For the pretty printer I"ve tried to not to use it at all, as I was editing in Eclipse and it was then changing to many lines.. But I could imagine that eclipse made it, that there was so many changes. Are you using SAP Gui Editor ?

**Comment by ivanfemia** [comment]
I'm using both.
I'll try to identify which is the conflict that GitHub raised.

Let me know if you can figure out before I do.

Thank you
Ivan

**Comment by fidley** [comment]
I've looked on the witer comparision and it seems that my version of SAPLink creates some new attributes for each class + this endmethod statement error which I listed before. I've also noticed that SAPLink has changed from UTF-8 to UTF-16.

image

**Comment by ivanfemia** [comment]
I included the pull request manually with fde89c9.

**Comment by fidley** [comment]
Ivan, 
had you found the reason of so many changes or it was SAPlink issue?

**Comment by ivanfemia** [comment]
I think that there is something with your saplink :(
I would suggest to reinstall it from scratch.

Ivan

Content mine, spelling by Apple

**Comment by StefanSchmoecker** [comment]
Hello Łukasz,

I think you are using a very outdated version of SAPLINK.  The "CREATED_BY" information has long been purged from the nuggets/slinkees

**Comment by fidley** [comment]
you were right, although I downloaded previously latest SAPLink, I haven't upgraded the plugins. Now when all is updated I have no problem with importing A2X nugget. Sorry for inconvenience.

**Pull request closed without merging**
