### PR TITLE
#323 excel converter

### PR DESCRIPTION
**Pull request by fidley**
Allowed to used objects which inherits from cl_gui_alv_grid

### CODE REVIEW

**Comment by review-ninja** [comment]
[ReviewNinja](http://app.review.ninja/ivanfemia/abap2xlsx/pull/352)

**Comment by ivanfemia** [comment]
Thank you Fidley, can you please also provide an example of usage... You can also create a new demo report

Ivan

**Comment by fidley** [comment]
I've done some programs in which I created a class which is inheriting from cl_gui_alv_grid. In such classes I usually add some common handling of toolbar and other events. Once done and can be reused within the project, but when I wanted to use A2X to bind ALV grid from my class this was not possible because you read only name of the class of object which was passed to bind_alv method. So I've added a check if passed class is not inheriting from other and if yes it's checking if this is one from handled by A2X. That's all. I don't think it needs a demo report. It's rather bug correction.

**Comment by ivanfemia** [comment]
Ok thank you for the explanation

**Pull request merged**
