### PR TITLE
#524 - code footprint reduction and #486 - cell value rich text formating

### PR DESCRIPTION
**Pull request by sigitas-stumbras**

### CODE REVIEW

**Comment by ivanfemia** [comment]
@sigitas-stumbras 
can you provide a short demo report of the functionality so we can add it to our demo show?

Thank you
Ivan

**Comment by ivanfemia** [comment]
@sigitas-stumbras

**Comment by ivanfemia** [comment]
This seems a great addition, but a  demo would be great to show the usage before committing

**Comment by AndreaBorgia-Abo** [comment]
I second @ivanfemia 's plea for a demo report and I also note that by now there are a number of conflicts to be solved.
Is this PR still valid?

**Comment by AndreaBorgia-Abo** [comment]
#781 was merged and resulted in some conflicts, sorry for the inconvenience.

**Comment by sandraros** [comment]
Hi @sigitas-stumbras I just came to see your PR, long time forgotten, but I think it would be really great to have in abap2xlsx. I understand that it has been a lot of time since you posted it, but I'd like to know if you can continue discussing. I can help like creating the demo program if needed. I would also like to propose to re-scope it to just rich text formatting. Do you think you could take some time to work on it again? If not, I would be very happy to integrate it anyway. Thanks.

**Comment by sandraros** [comment]
I'm splitting the changes of PR #531 in two parts:
- Towards fixing #486
  - #851
  - #852
- New PRs to fix #524 
  - #929 
  - #930

**Comment by sandraros** [comment]
All replacement pull requests are now merged, closing this now obsolete PR.
@AndreaBorgia-Abo Thank you for your help!
@sigitas-stumbras You may verify, and delete your fork/branch if you wish.

**Pull request closed without merging**
