### PR TITLE
Support for comments (Issue #180)

### PR DESCRIPTION
**Pull request by guillaumegarcia13**
Supporting Cell comments include:
- changing [Content_Types].xml to support vmlDrawings
- generate a new file comments[index].xml within the /xl folder
- reference the relationship to the comments[index].xml in \xl\worksheets_rels\sheet[index].xml.rels
- add a new drawing (for displaying the comment itself) in \xl\drawings\vmlDrawing[index].vml
- reference the new drawing in \xl\worksheets_rels\sheet[index].xml.rels

Generated Excel is attached
[Comments.xlsx](https://github.com/ivanfemia/abap2xlsx/files/71680/Comments.xlsx)

### CODE REVIEW

**Comment by larshp** [comment]
suggest closing this PR, and opening a new for the latest version

**Comment by larshp** [comment]
suggest closing this PR, and opening a new for the latest version

**Comment by ivanfemia** [comment]
I would like to find time to introduce this functionality... I'm keeping this on old to have a quick reference on the changes

**Comment by ivanfemia** [comment]
This is on hold once someone has time to align the releases

**Comment by sigitas-stumbras** [comment]
Hello,

This support for comments functionality is something I will probably be needing for my project. Although I am having hard time getting my head around the idea of how the alignment non-automaticaly-mergeable branches/pull requests is to be carried out. Especially in the context of ABAP. I'd really appreciate any links or pointers.

**Comment by ivanfemia** [comment]
This was an old contribution, that now is too old to be merged in the main line.
I keep this as a reference if I have time in the future to re-implement the same or anyone else to implement the same feature

**Comment by JanWerder** [comment]
Okay, just for future reference or anybody who is struggeling with this.

If you manually add all the changes from above it takes a couple of hours, but it still works.
There are a few changes you have to do, that are not in the sources above.

1. The Content Types are wrong. You need a comment# and a vml node in addition to the nodes that are already there [1]
2. The Capitalization in the sheet relation (i.e. sheet1.xml.rels) is wrong. The ids are all lower case, but they need to be capitalized.

A good workflow is to let excel repair the file and the compare the files until it matches.

[1]
```
<Override PartName="/xl/comments1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"/>
<Default Extension="vml" ContentType="application/vnd.openxmlformats-officedocument.vmlDrawing"/>
```

**Comment by ivanfemia** [comment]
Jan,

can you propose a pull request with this enhancement?
It would be great to add the feature in the main release, instead of having
everyone doing the changes manually.

Ivan

**Comment by btptv** [comment]
how do I download these? I can't use abapgit behind the firewall

**Comment by Mind-Open** [comment]
@Btptv use saplink ..

**Comment by larshp** [comment]
use the offline feature, https://docs.abapgit.org/guide-import-zip.html

Update: as this is a very old PR it is in saplink format

**Comment by btptv** [comment]
Lars,   mind_open  
Thanks for the reply! I downloaded but was have some trouble getting it working.   Some of he slnk do not seem to load. I may have to figure it out but in the meantime  I was wondering does the ability to add macros to the workbook work?  It may be easier to just code my sap app to  put a macro in that call .add_comment in the work sheet

**Comment by gregorwolf** [comment]
I've created #583 with the changes from @guillaumegarcia13.
@larshp please crosscheck.

**Pull request closed without merging**
