### PR TITLE
Add ability to generate report from template

### PR DESCRIPTION
**Pull request by AntonSikidin**
I just add some automation to remove routine manual work when you create report from template.

add 

- ZIF_EXCEL_READER->LOAD_SMW0  to load template from smw0
- ZCL_EXCEL->FILL_TEMPLATE to merge template with data
- ZCL_EXCEL_TEMPLATE_DATA  -  class to hold data
- ZCL_EXCEL_FILL_TEMPLATE  - class that merge data with template

change 

- ZCL_EXCEL_WORKSHEET->MT_MERGED_CELLS type to public

complete article with examples, instruction how to use it

https://blogs.sap.com/2020/05/22/best-way-to-generate-microsoft-excel-xlsx-from-template-in-abap/

### CODE REVIEW

**Comment by AntonSikidin** [comment]
Please, help me.

What wrong with TYPES?

**Comment by larshp** [comment]
`EMPTY KEY` does not exist in 702

**Comment by AntonSikidin** [comment]
Do I need additional proactive steps on my part to merge the code?

**Comment by sandraros** [comment]
I hope this new feature will be quickly approved and merged. It will accelerate Excel development a lot.

**Comment by larshp** [comment]
@AntonSikidin check conflicts

**Comment by AndreaBorgia-Abo** [comment]
#781 was merged and resulted in some conflicts, sorry for the inconvenience.

**Comment by sandraros** [comment]
@AntonSikidin I am currently reviewing your PR, I will solve the conflicts and do some proposal soon.

**Comment by sandraros** [comment]
Dear Anton, owners and contributors,
First of all, Anton, sorry for the delay for reviewing such a great improvement. As it's quite complex, it took some time to review your PR, so I preferred to not solicit you again for all intermediate merged PRs during the review.
I'd like to propose some little changes and I need your opinion and approval. I also solicit owners and contributors for the same because it's an important improvement (@AndreaBorgia-Abo @gregorwolf @larshp etc.). I made Anton's solution + proposed changes available here: https://github.com/sandraros/abap2xlsx/tree/New-Review-of-AntonSikidin. Below is the list of all my points and questions.
The tool is described in the link above posted by Anton.
Thanks for reading and helping me.
Sandra

As I propose many (but little) changes, I first describe the major changes which are most impacting:
- Changes impacting people who already use Anton's fork:
  - Removal of DDIC objects, replaced by class types (to reflect current abap2xlsx trends to not use DDIC objects, unless mandatory)
  - Some public members from `ZCL_EXCEL_FILL_TEMPLATE` were turned into private: all the methods (one public method CREATE was added to call them) and the attribute `mt_merged_cells`.
  - People who made some forks may be disturbed by renamed local variables and renamed private types, and the many little changes.
- Noticeable improvements:
  - Program `ZDEMO_EXCEL_GET_TYPES` (generator of `TYPES` statements based on the Excel template file): it can propose automatically the types string, t_number, D and T, based on cell number formats, to reduce the adaptation work.
  - Coding (internal): I removed some code by using existing abap2xlsx methods like SET_CELL, DELETE_MERGE and SET_MERGE.
- More questions:
  - Should we keep the new method LOAD_SMW0? (the goal is to load Excel template files from SMW0) I personally agree with that (con: there are other possibilities to store files, if we do it for SMW0, there's no reason to refuse other people proposing other methods ; pro: providing one way to deliver Excel file demos with abap2xlsx is a good point, and we can say it will be the only method provided by abap2xlsx)
  - I preferred to place the program `ZDEMO_EXCEL_GET_TYPES` in the _demos package. This program is essential in proposing automatically the `TYPES` coding, but it's neither a demo program nor an abap2xlsx runtime program, it's made to help people create their programs quickly. I don't think another package is to be created, but maybe should it be placed in the main package?

Proposed detailed changes:
- General proposal: use abap2xlsx coding guidelines everywhere:
  - There's a new naming proposal [here](https://github.com/sapmentors/abap2xlsx/blob/master/docs/contributing/coding-guidelines.md), that I applied to the private and local objects, but not to the exposed names (public objects, parameters) because the tool is already published.
  - There are new DDIC objects that I propose to remove because we are trying to not create any more DDIC object in abap2xlsx (and even removing them). I hope that it will not have too much impact on existing installations.
  - DATA, FIELD-SYMBOLS, etc., are moved to the top of each procedure instead of placing them in the middle of procedures (right before usage).
  - Position of dot and comma in chained statements, proposing to have:
    ```
    DATA: lv_var1,
      lv_var2.
    ```
    instead of:
    ```
    DATA
         : lv_var1
         , lv_var2
         .
    ```
  - AND/OR on two lines, proposing to have:
    ```
    LOOP AT ... WHERE field1 = field1
                  AND field2 = field2
                  AND field3 = field3.
    ```
    instead of:
    ```
    LOOP AT ... WHERE field1 = field1 AND
                      field2 = field2 AND
                      field3 = field3.
    ```
- New program `ZDEMO_EXCEL_FILL_TEMPLATE`
  - Proposal: change package to _demos
  - Proposal: default choice changed to read the Excel template from the demo example in the MIME Repository, so that people can immediately execute and see the result.
  - Proposal: replace obsolete `OCCURS` with `TYPE STANDARD TABLE`.
  - Proposal: change path from `C:\Users\sadfasdf\Desktop\abap2xlsx\ZABAP2XLSX_EXAMPLE.xlsx` to `c:\temp\whatever.xlsx` as in `ZDEMO_EXCEL37`.
  - Proposal: handle exceptions if file is not found, etc., to avoid short dumps.
  - Proposal: change type of date and time fields from respectively C 10 and C 8 to D and T, so that to provide a more convenient example. Note that the Excel template file has been updated accordingly to have cells with date and time number formats.
- Changed class `ZCL_EXCEL`
  - New method `FILL_TEMPLATE`
    - Proposal: replace calls to the 4 methods CREATE OBJECT, GET_RANGE, SIGN_RANGE and FIND_VAR from ZCL_EXCEL_FILL_TEMPLATE, by unique new method CREATE from ZCL_EXCEL_FILL_TEMPLATE.
- Changed class `ZCL_EXCEL_WORKSHEET`
  - New attribute `mt_merged_cells`
    - Proposal: keep it private instead of making it public (see reason in `zcl_excel_fill_template`)
- New class `ZCL_EXCEL_FILL_TEMPLATE`
  - Proposal: turn all public methods into private, except FILL_SHEET (called by method FILL_TEMPLATE of ZCL_EXCEL) and create method CREATE (calls the other methods which are now private) which calls CREATE OBJECT, GET_RANGE, DISCARD_OVERLAPPED, SIGN_RANGE.
  - Proposal: public attributes should be READ-ONLY
  - The proposed changes imply adding RAISING zcx_excel in the methods.
  - New attribute `MT_NAME_STYLES` filled by method `FIND_VAR`; it's used by program ZDEMO_EXCEL_GET_TYPES to determine the best ABAP type based on the number format of cells. NB: t_number is currently arbitrarily set to `type P length 16 decimals 4` as `decfloat16` is currently not supported by abap2xlsx.
  - Method `validate_range`
    - Proposal: extend possible ranges from row form `1:1` to equivalent cell form `A1:XFD1`, so that these ranges can be generated by abap2xlsx
  - Method `find_var`
    - Proposal: initialize the new attribute `MT_NAME_STYLES`.
  - Method `fill_sheet`
    - Proposal: use DELETE_MERGE and SET_MERGE instead of changing attribute MT_MERGED_CELLS from private to public to change its value directly. Added RAISING zcx_excel in the method signature.
  - Method `fill_range`
    - Proposal: rename parameter `CH_DIFF` into `CV_DIFF`
    - Proposal: replace `LOOP AT EXIT` with `READ TABLE`
    - Proposal: review the logic of Excel `[variable]` replacement by calling the method `SET_CELL` of `ZCL_EXCEL_WORKSHEET` which handles it nicely. That also avoids referring to `cl_abap_typedescr=>typekind_int8` which does not exist in 7.02.
  - Method `get_range`
    - OK
  - Method `sign_range`
    - OK
  - Method `discard_overlapped`
    - OK
- New DDIC structures and types
  - Proposal: replace them with types in classes or other same existing types.
    ```
    DDIC Object                    Replacement
    -----------------------------  ----------------------------------------
    zexcel_s_template_data         ts_template_data_sheet    in zcl_excel_template_data
    zexcel_t_template_data         ts_template_data_sheets   in zcl_excel_template_data
    zexcel_template_s_range        ts_range                  in zcl_excel_fill_template
    zexcel_template_s_var          ts_variable               in zcl_excel_fill_template
    zexcel_template_sheet_title    zexcel_sheet_title (DDIC)
    zexcel_template_t_cell_data    private type tt_cell_data_no_key in zcl_excel_fill_template
    zexcel_template_t_range        tt_ranges                 in zcl_excel_fill_template
    zexcel_template_t_sheet_title  tt_sheet_titles           in zcl_excel_template_data
    zexcel_template_t_var          tt_variables              in zcl_excel_fill_template
    ```
- New program `ZDEMO_EXCEL_GET_TYPES`
  - Proposal: change package to _demos
  - Proposal: propose types t_number (arbitrarily set to P length 16 decimals 4), date, time or string based on cell number format (thanks to new attribute `MT_NAME_STYLES` of ZCL_EXCEL_FILL_TEMPLATE)
  - Proposal: change path from `C:\Users\sadfasdf\Desktop\abap2xlsx\ZABAP2XLSX_EXAMPLE.xlsx` to `c:\temp\whatever.xlsx` as in program `ZDEMO_EXCEL37`.
  - Proposal: Replace calls to CREATE OBJECT, GET_RANGE, DISCARD_OVERLAPPED, SIGN_RANGE, FIND_VAR with the call to the new method CREATE
  - Proposal: instead of generating obsolete code `OCCURS 0`, use `TYPE STANDARD TABLE OF ... WITH DEFAULT KEY` (compatible 7.02)
- New class `ZCL EXCEL TEMPLATE DATA`
  - Proposal: add READ-ONLY to MT_DATA
- Changed interface `ZIF_EXCEL_READER`
  - New Method `LOAD_SMW0`
    - OK
- Changed class `ZCL_EXCEL_READER_2007`
  - New Method `zif_excel_reader~LOAD_SMW0`
    - Removal of cl_bcs_convert=>xtab_to_xstring (because it returns a XSTRING with extra null bytes and I prefer to avoid future issues) by using WWWPARAMS_READ (to read the 'filesize' attribute) and SCMS_BINARY_TO_XSTRING
- `ZEXCEL_DEMO_TEMPLATE` (binary MIME object in SMW0)
  - Proposal: change package to _demos
  - Proposal: change MIME type from `xlsx` to `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` as there are more chances to have the latter one already configured in SAP systems (?)
  - Proposal: change number format of cells containing date and time fields to reflect the changed types of program `ZDEMO_EXCEL_FILL_TEMPLATE`, to be respectively D and T. The chosen number formats are the ones that will reflect the Windows user's regional format (e.g. m/d/yyyy for USA people, dd/mm/yyyy for French people, etc.)
- `ZDEMO_FILL_TEMPLATE` (transaction code)
  - Proposal: remove it as other demo programs don't have transaction codes. There is also the central demo program `ZABAP2XLSX_DEMO_SHOW` which automatically adds `ZDEMO_EXCEL_FILL_TEMPLATE` in the list of demo programs.

**Comment by AndreaBorgia-Abo** [comment]
Ok, at long last here are my thoughts: 

* LOAD_SMW0: I'm in favour of keeping this method, however I wonder if we can build some additional flexibility in the system, just not too much: a generic "LOAD" method in a dedicated interface, then we provide an implementation against SMW0. This way, one could swap in an implementation for server-side local files, archival systems, and so and so forth. Oh and... do we even have SMW0 on BTP?

* Placement of ZDEMO_EXCEL_GET_TYPES: I agree, the types assistant belongs to the main package, since it doesn't demo any existing features of the library, unlike the template filler which indeed does that. The report name should consequently lose the "DEMO" part, for example "ZEXCEL_GET_TYPES".

* Comma positioning: the alternate style is only useful when commenting out code to disable it, with git it makes little sense to adopt it. In favour of "comma at end".

* AND/OR positioning: no opinion on this, I tend to side with the proposal but I'm sure I have occasionally written the other format.

* ZCL_EXCEL_FILL_TEMPLATE: went looking for the reason "mt_merged_cells" is proposed private in the code, instead of later on in the comment, found "excell" (double L) in description. I swear I wasn't looking for typos, they're just happy to see me! ;)

**Comment by sandraros** [comment]
Just saw this older discussion #452 about introducing a MIME Repository reader, and the answer was mostly NO. Maybe we should stay on that decision, and the code to read the MIME file should be moved to the the demo program? There is also this discussion #632 to move abap2xlsx to ABAP Cloud (BTP), I would think that it doesn't support the MIME Repository. Because of the latter discussion, I would propose to have `ZDEMO_EXCEL_GET_TYPES` in the new folder "not_cloud", because the program displays a dynpro (Cloud-incompatible).
NB: I'll try to push the changes proposed above to AntonSikidin:master this week-end.

**Comment by AndreaBorgia-Abo** [comment]
> Maybe we should stay on that decision, and the code to read the MIME file should be moved to the the demo program?

It comes down to these two considerations, compatibility with BTP and "core business", so to speak: this project deals with reading / writing XLSX, where from / to is not really our business. I withdraw my suggesion for a generic LOAD, makes no sense now.

Ok for "not cloud" as location for the new report.

**Comment by sandraros** [comment]
I have pushed new commits to [Anton branch](https://github.com/AntonSikidin/abap2xlsx).

These latest changes are as discussed:
- moved the program `ZEXCEL_TEMPLATE_GET_TYPES` to the package "not_cloud" (this program was originally named `ZDEMO_EXCEL_GET_TYPES`, I renamed it because it's not a demo)
- removed all the `SMW0` stuff from `ZIF_EXCEL_READER` and `ZCL_EXCEL_READER_2007` (reason: #452 and #632), and have a subroutine `LOAD_SMW0` locally defined in programs `ZEXCEL_TEMPLATE_GET_TYPES` and `ZDEMO_EXCEL_FILL_TEMPLATE`. People currently using Anton version will have to review their programs if they use these SMW0 methods.

Additionally, I have:
- renamed the Web Repository Excel file `ZEXCEL_DEMO_TEMPLATE` to `ZDEMO_EXCEL_TEMPLATE` to keep the names consistent with all demo objects (`ZDEMO_EXCEL_*`).

Now I think we can go a step further to see if everybody agrees with the latest proposals, and maybe merge this really nice feature. 😀

**Review by AndreaBorgia-Abo — APPROVED** [review]

**Comment by sandraros** [comment]
Finally done! 🥳 Maybe it's worth a blog post on SAP Community...

**Comment by AndreaBorgia-Abo** [comment]
@sandraros I'm not sure you believe in coincidences, but let me tell you the story: I'm writing a guide to abap2xlsx for my coworkers and I found this conversation while trying to document templates handling. At the same time, @Keller-Michael posted ["our future requires engagement"](https://blogs.sap.com/2022/02/10/our-future-requires-engagement/).
Does this count as a sign? :)

**Pull request merged**
