### PR TITLE
remove XFELD

### PR DESCRIPTION
**Pull request by AndreaBorgia-Abo**
see https://github.com/sapmentors/abap2xlsx/issues/692

As a starting point, I've changed "xfeld" (as domain) to "abap_bool" in the source code;
I am unsure whether we also want to change the data elements (example, ZEXCEL_BOOK_PROTECTION) or not, just let me know and I can do that too.

### CODE REVIEW

**Comment by larshp** [comment]
ZEXCEL_BOOK_PROTECTION:

its actually a XFELD with 4 values, https://github.com/sapmentors/abap2xlsx/blob/master/src/zif_excel_book_protection.intf.abap,
```
  CONSTANTS c_locked TYPE zexcel_book_protection VALUE '1'. "#EC NOTEXT
  CONSTANTS c_protected TYPE zexcel_book_protection VALUE 'X'. "#EC NOTEXT
  CONSTANTS c_unlocked TYPE zexcel_book_protection VALUE '0'. "#EC NOTEXT
  CONSTANTS c_unprotected TYPE zexcel_book_protection VALUE ''. "#EC NOTEXT
```

anyhow, in my opinion, it looks like this data element can be replaced with a type defined in interface `zif_excel_book_protection`, only reason to have it as a data element would be saving in database or using in a dynpro, which I don't think will happen?

**Review by larshp — APPROVED** [review]
looks good to me, I'll wait a while merging it, to allow others to also review

**Comment by AndreaBorgia-Abo** [comment]
Thanks :)
I synced my repo by cloning and merging on my Linux desktop, is there a better way to do this?
This bit is not entirely clear from the docs.

**Comment by larshp** [comment]
its described at https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

sometimes I also just delete the fork and refork it

**Comment by AndreaBorgia-Abo** [comment]
I know the workflow, I'm having trouble understanding how I can follow it with abapGit alone, if at all possible.
EDIT: looks like the best way is to work in tandem with another git client simply to fetch upstream and merge.

**Comment by AndreaBorgia-Abo** [comment]
> anyhow, in my opinion, it looks like this data element can be replaced with a type defined in interface `zif_excel_book_protection`, only reason to have it as a data element would be saving in database or using in a dynpro, which I don't think will happen?

I compared zif_excel_book_protection with zif_excel_sheet_protection and I'm considering these changes:
* clone data element "zexcel_sheet_protection_bool" to "zexcel_book_protection_bool"
* in "zexcel_book_protection" change c_locked  and c_unlocked to "zexcel_book_protection_bool"
* change both zexcel_book_protection and zexcel_sheet_protection to local types

Looks reasonable?

**Comment by larshp** [comment]
@AndreaBorgia-Abo suggest moving above comment to a new open issue

**Comment by AndreaBorgia-Abo** [comment]
> As a starting point, I've changed "xfeld" (as domain) to "abap_bool" in the source code;

Most likely, I had already performed the following checks before but during #775 this point was raised so I am documenting the checks here for completeness:

class zcl_excel_worksheet, method set_table: 
* ip_transpose and ip_no_header were typed xfeld prior to #714 but the implementation checks against abap_true (safe change)

class zcl_excel, member USE_TEMPLATE:
* typed xfeld but checked in method create against abap_true (safe change)
* in report ZDEMO_EXCEL37 it is explicitly set to abap_true (safe change)

report ZEXCEL_DEMO19 and ZDEMO_EXCEL15, parameter p_noout:
* typed xfeld but checked against abap_false (arguably safer now)

**Pull request merged**
