### PR TITLE
Address DDIC Issues on BTP ABAP Environment: SAP_BASIS 794 (SAPK-79406INSAPBASIS  0006)

### PR DESCRIPTION
**Pull request by attilaberencsi**
Hello Devs,

I created a fork and pulled it in the current Trial BTP ABAP Environment.
I solved remaining DDIC structure activation issues regarding dynpro/screen related data elements, which are not released in BTP ABAP Environment.

The fix approach was to copy each unreleased data elements and domains as zexcel_<meaningful_english_name> and replaced them in structures

- zexcel_s_converter_col
- zexcel_s_converter_fcat
- src/zexcel_s_fieldcatalog

One additional foreign key check had to be removed as well, due access to DDIC tables is not allowed on BTP.

kép

Thank You, BR, Attila

### CODE REVIEW

**Comment by sandraros** [comment]
Thank you. I guess there's no issue in merging your proposal, except I would remove the non-English translations if you don't mind, just to keep abap2xlsx consistent (I guess all texts are provided in English only). I will check it as quick as I can.

**Comment by attilaberencsi** [comment]
Unlike onPremise I'm not able to do it in the Cloud.
https://answers.sap.com/questions/13626538/adtbtp-abap-environment-how-to-change-original-lan.html
What I can do, is that I pull my fork to my 1909 minisap and adjust the original language to english there replacing any remaining german texts. Then I create a new pull request. We can cancel this then. Is that fine :) ?

**Comment by sandraros** [comment]
I guess the original language is English for all your objects, it's only the non-English translations to remove. I was thinking to download the files as ZIP and remove manually the translations, it should not take long.

**Comment by larshp** [comment]
as found in https://github.com/abap2xlsx/abap2xlsx/pull/1169/checks?check_run_id=20032031907, with https://github.com/abap2xlsx/abap2xlsx/pull/872 created in 2021 I suggest moving the field catalog stuff to a separate folder.

There is no field catalog concept in ABAP Cloud, adding more data elements will just be legacy IMHO

**Comment by attilaberencsi** [comment]
I will create few more commits for the mentioned items:
- move the touched dynpro related structures and data elements to subpackage: _NOT_ABAP_CLOUD
- remove non english translations

**Comment by attilaberencsi** [comment]
Hi, 
@sandraros translations where removed from the abapGit source files. 
@larshp : moved the data elements and domains to NOT_ABAP_CLOUD subpackage
Thanks, Attila

**Comment by sandraros** [comment]
NB: the PR should fix #692.

**Comment by sandraros** [comment]
Current situation with SAP S/4HANA Public Cloud, filtering the Dictionary Log on "error", and some comments (e.g. "foreign key"):
```
TABL ZEXCEL_S_CONVERTER_COL was not activated                         error  D0(408)
    The use of Data Element LVC_NOKEYC is not permitted.                  error  LA(020)
TABL ZEXCEL_S_CONVERTER_FCAT was not activated                        error  D0(408)
    The use of Data Element CONVEXIT is not permitted.                    error  LA(020)
    The use of Data Element LVC_COLID is not permitted.                   error  LA(020)
    The use of Data Element SCRTEXT_L is not permitted.                   error  LA(020)
    The use of Data Element SCRTEXT_M is not permitted.                   error  LA(020)
    The use of Data Element SCRTEXT_S is not permitted.                   error  LA(020)
    The use of Data Element TABFDPOS is not permitted.                    error  LA(020)
    The use of Table DD02L is not permitted.                              error  LA(020)   (foreign key)
TABL ZEXCEL_S_FIELDCATALOG was not activated                          error  D0(408)
    The use of Data Element DYNPROFLD is not permitted.                   error  LA(020)
    The use of Data Element SCRTEXT_L is not permitted.                   error  LA(020)
    The use of Data Element SCRTEXT_M is not permitted.                   error  LA(020)
    The use of Data Element SCRTEXT_S is not permitted.                   error  LA(020)
    The use of Data Element TABFDPOS is not permitted.                    error  LA(020)
TTYP ZEXCEL_T_CONVERTER_COL was not activated                         error  D0(408)
    Row type ZEXCEL_S_CONVERTER_COL is not active or does not exist       error  DO(845)
TTYP ZEXCEL_T_CONVERTER_FCAT was not activated                        error  D0(408)
    Row type ZEXCEL_S_CONVERTER_FCAT is not active or does not exist      error  DO(845)
TTYP ZEXCEL_T_FIELDCATALOG was not activated                          error  D0(408)
    Row type ZEXCEL_S_FIELDCATALOG is not active or does not exist        error  DO(845)
```
List of the data elements created to replace unreleased data elements:
```
Old            New
----------    ---------------------------
LVC_NOKEYC    ZEXCEL_KEY_COLOR_OVERRIDE
CONVEXIT      ZEXCEL_CONVEXIT
LVC_COLID     ZEXCEL_COLUMN_ID
SCRTEXT_L     ZEXCEL_DISP_TEXT_LONG
SCRTEXT_M     ZEXCEL_DISP_TEXT_MEDIUM
SCRTEXT_S     ZEXCEL_DISP_TEXT_SHORT
TABFDPOS      ZEXCEL_COMPONENT_POSITION
DYNPROFLD     ZEXCEL_SCREEN_DISPLAY
```

**Comment by sandraros** [comment]
@larshp @attilaberencsi  I'd propose for now to keep `ZEXCEL_S_FIELDCATALOG` in the main package because it's not used only for ALV but also for non-ALV features (unfortunately):
- `ZCL_EXCEL_READER_2007`
- `ZCL_EXCEL_TABLE`
- `ZCL_EXCEL_WORKSHEET`
- `ZCL_EXCEL_WRITER_2007`
(and `ZCL_EXCEL_CONVERTER` which is not Cloud)

Are you okay to create an issue to refactor it later?

NB: apart this, I'm okay to merge the pull request (that will let the place to prepare the huge fixing of ~400 syntax errors in ABAP programs in SAP BTP)

**Comment by attilaberencsi** [comment]
Thanks You Sandra, from my site this is OK.

**Comment by larshp** [comment]
@sandraros ok

**Comment by sandraros** [comment]
@attilaberencsi @larshp Thank you for your great help, it's merged.

**Comment by larshp** [comment]
Hi,
Idea was to have the "not_cloud" isolated, there is a reference in /src/ which uses /src/not_cloud/ object,

image

https://abaplint.app/stats/abap2xlsx/abap2xlsx/package_coupling?folder=/src

image

not_cloud using src: ok

src using not_cloud: bad, I think the CLAS reference was already there, it requires refactoring

**Pull request merged**
