### PR TITLE
Support for comments (Issue #180)

### PR DESCRIPTION
**Pull request by gregorwolf**
As contributed by @guillaumegarcia13

### CODE REVIEW

**Comment by larshp** [comment]
looks okay, however, I did not test it

I think we should consider adding some development guidelines, eg use of pretty printer + do we prefix or not prefix, I have suggestions for both, however just find it important to align across the code in the project

**Comment by larshp** [comment]
lets just merge it?

**Comment by ivanfemia** [comment]
Merged

**Comment by jonothomask** [comment]
I noticed that comments are not displaying in the second sheet if no comments set in the first sheet.

**Comment by larshp** [comment]
@jonothomask please open an issue for the found issue

**Pull request merged**
