### PR TITLE
add steampunk linting setup

### PR DESCRIPTION
**Pull request by larshp**
this adds a steampunk linting setup, #632

with every commit, another status is reported for the Steampunk compatiblity,
image

### CODE REVIEW

**Comment by larshp** [comment]
from 1251 issues down to 929 issues with the latest changes to main branch

**Comment by larshp** [comment]
down to 656 issues

**Comment by larshp** [comment]
down to 349 issues (converter classes moved)

**Comment by larshp** [comment]
suggest merging

**Comment by sandraros** [comment]
@AndreaBorgia-Abo @gregorwolf I'm incompetent to assess the PR myself, could you help?

**Comment by AndreaBorgia-Abo** [comment]
I'm the same boat ;(
I only have the demo BTP account, which is shared and already has abap2xlsx in it.

**Comment by larshp** [comment]
this PR only adds extra static analysis _information_ in the PR

image

no actual code changes

**Comment by AndreaBorgia-Abo** [comment]
> this PR only adds extra static analysis _information_ in the PR
> no actual code changes

I know, I know but how do we check for correctness? I mean, other than observing that the linter did not complain for your commits.

**Comment by larshp** [comment]
correctness: not for now, first we need to fix the findings, when the number is reduced, we can start importing into a real Steampunk system to verify

**Comment by sandraros** [comment]
Shouldn't we put extra effort now to fix these 380 messages before merging this PR?

**Comment by AndreaBorgia-Abo** [comment]
@sandraros Given that the messages are simple warnings and that we're not in the position to carry out a proper review, I'd say @larshp can go ahead with the merge and we'll handle the results in due time, referring to either this issue or #692 as required.

**Review by AndreaBorgia-Abo — APPROVED** [review]
as noted, I'm not able to evaluate these changes.
proposing to merge since they only introduce warnings after future merges.

**Comment by gregorwolf** [comment]
@AndreaBorgia-Abo If you would like to get your own BTP ABAP Environment you can register as a private person for [BTP Free Tier](https://www.sap.com/products/business-technology-platform/trial.html)

**Comment by AndreaBorgia-Abo** [comment]
I know, I have it. The free tier, however, is shared and this limits the
possibilities of development

**Comment by gregorwolf** [comment]
I think you mix Free Tier with Trial. Trial is shared.

**Comment by larshp** [comment]
merging, note that the check is not required, does not give errors, its just for transparency

lets see how it goes, can always disable it

**Pull request merged**
