### PR TITLE
Erratic naming convention of variables

### PR DESCRIPTION
**Pull request by sandraros**
That's a proposal to be discussed.
Note that I didn't add a link in the Contributing Guidelines.

### CODE REVIEW

**Review by AndreaBorgia-Abo — APPROVED** [review]
Given an impossible task, this is the best we can do to maintain some semblance of sanity.
Thank you for the summary, I think we may add it to the project and I'll link to it in contributing.md once done.

**Comment by AndreaBorgia-Abo** [comment]
At the moment we have all misc documentation under docs/ and there is no docs/contributing/ subdir.
I suggest that we move this file one level up and forego the additional subdir.
(I have added the link to CONTRIBUTING.md in #769 assuming the suggestion is acceptable)

**Comment by larshp** [comment]
approved above, merging

**Comment by AndreaBorgia-Abo** [comment]
Uhm, we now have a docs/contributing/ directory: do we keep it? If so, I'll fix the link in CONTRIBUTING.md

**Pull request merged**
